datalinks = [[None, None, None, None, None],
 [None, None, None, None, None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://www.cidrap.umn.edu/robots.txt', None, None, None, [], None],
 ['https://www.gov.uk/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.gov.uk/sitemap.xml'],
  None],
 [None, None, None, None, None],
 ['https://www.ecb.europa.eu/robots.txt',
  None,
  'https://www.ecb.europa.eu/rss',
  None,
  ['sitemap: https://www.ecb.europa.eu/sitemap.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://www.govinfosecurity.com/robots.txt',
  'https://www.govinfosecurity.com/sitemap_index.xml',
  'https://www.govinfosecurity.com/rss',
  'https://www.govinfosecurity.com/rss2',
  [],
  None],
 ['https://www.turkiyenewspaper.com/robots.txt', None, None, None, [], None],
 ['https://www.techradar.com/robots.txt',
  None,
  'https://www.techradar.com/rss',
  None,
  ['# sitemaps                                       #',
   'sitemap: https://www.techradar.com/sitemap.xml',
   'sitemap: https://www.techradar.com/sg/sitemap.xml',
   'sitemap: https://www.techradar.com/uk/sitemap.xml',
   'sitemap: https://www.techradar.com/au/sitemap.xml',
   'sitemap: https://www.techradar.com/nz/sitemap.xml',
   'sitemap: https://global.techradar.com/es-mx/sitemap.xml',
   'sitemap: https://global.techradar.com/da-dk/sitemap.xml',
   'sitemap: https://global.techradar.com/fi-fi/sitemap.xml',
   'sitemap: https://global.techradar.com/no-no/sitemap.xml',
   'sitemap: https://global.techradar.com/sv-se/sitemap.xml',
   'sitemap: https://global.techradar.com/it-it/sitemap.xml',
   'sitemap: https://global.techradar.com/nl-nl/sitemap.xml',
   'sitemap: https://global.techradar.com/nl-be/sitemap.xml',
   'sitemap: https://global.techradar.com/fr-fr/sitemap.xml',
   'sitemap: https://global.techradar.com/de-de/sitemap.xml',
   'sitemap: https://global.techradar.com/es-es/sitemap.xml'],
  None],
 ['https://coinmarketcap.com/robots.txt', None, None, None, [], None],
 ['https://www.drybulkmagazine.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.drybulkmagazine.com/sitemap.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://www.the-star.co.ke/robots.txt',
  None,
  'https://www.the-star.co.ke/rss',
  None,
  ['disallow: /classifieds/sitemaphandler/'],
  None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 ['https://kuwaittimes.com/robots.txt',
  None,
  'https://kuwaittimes.com/rss',
  None,
  [],
  None],
 ['https://www.osce.org/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.osce.org/sitemap.xml'],
  None],
 ['https://www.independent.ie/robots.txt',
  None,
  'https://www.independent.ie/rss',
  None,
  ['# sitemap files',
   'sitemap: https://www.independent.ie/sitemap/sitemap_googlenews.xml',
   'sitemap: https://www.independent.ie/sitemap/sitemap_channels.xml',
   'sitemap: https://www.independent.ie/sitemap/sitemap.xml',
   'sitemap: https://www.independent.ie/sitemap/sitemap_video.xml'],
  None],
 ['https://www.trtworld.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.trtworld.com/sitemap.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://uk.practicallaw.thomsonreuters.com/robots.txt',
  'https://uk.practicallaw.thomsonreuters.com/sitemap_index.xml',
  'https://uk.practicallaw.thomsonreuters.com/rss',
  'https://uk.practicallaw.thomsonreuters.com/rss2',
  ['sitemap: https://uk.practicallaw.thomsonreuters.com/sitemap.xml'],
  None],
 [None, None, None, None, None],
 ['https://www.risk.net/robots.txt', None, None, None, [], None],
 ['https://apnews.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://apnews.com/ap-sitemap.xml',
   'sitemap: https://apnews.com/news-sitemap-content.xml',
   'sitemap: https://apnews.com/video-sitemap.xml',
   'sitemap: https://apnews.com/buyline-personal-finance/sitemap.xml'],
  None],
 ['https://www.gmanetwork.com/robots.txt',
  'https://www.gmanetwork.com/sitemap_index.xml',
  'https://www.gmanetwork.com/rss',
  None,
  ['sitemap: https://www.gmanetwork.com/news/sitemap-news.xml',
   'sitemap: https://www.gmanetwork.com/sitemap-entertainment-revamp.xml'],
  None],
 ['https://www.youtube.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.youtube.com/sitemaps/sitemap.xml',
   'sitemap: https://www.youtube.com/product/sitemap.xml'],
  None],
 [None, None, None, None, None],
 ['https://www.legit.ng/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.legit.ng/legit/sitemap/www/sitemap.xml',
   'sitemap: https://www.legit.ng/legit/sitemap/www/news.xml',
   'sitemap: https://www.legit.ng/legit/sitemap/www/category-sitemap.xml',
   'sitemap: https://www.legit.ng/legit/sitemap/www/tag-sitemap.xml',
   'sitemap: https://www.legit.ng/legit/sitemap/www/author-sitemap.xml',
   'sitemap: https://www.legit.ng/legit/sitemap/www/expert-sitemap.xml',
   'sitemap: https://www.legit.ng/legit/sitemap/www/static-sitemap.xml'],
  None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 ['https://www.irishtimes.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.irishtimes.com/arc/outboundfeeds/sitemap/',
   'sitemap: https://www.irishtimes.com/arc/outboundfeeds/sitemap-days/',
   'sitemap: https://www.irishtimes.com/arc/outboundfeeds/sitemap-news-index/',
   'sitemap: https://www.irishtimes.com/arc/outboundfeeds/sitemap-section-index/',
   'sitemap: https://www.irishtimes.com/arc/outboundfeeds/sitemap-section/',
   'sitemap: https://www.irishtimes.com/arc/outboundfeeds/video-sitemap/'],
  None],
 ['https://www.laprensalatina.com/robots.txt',
  'https://www.laprensalatina.com/sitemap_index.xml',
  'https://www.laprensalatina.com/rss',
  'https://www.laprensalatina.com/rss2',
  ['sitemap: https://www.laprensalatina.com/sitemap_index.xml'],
  None],
 [None, None, None, None, None],
 ['https://www.benzinga.com/robots.txt',
  'https://www.benzinga.com/sitemap_index.xml',
  None,
  None,
  ['sitemap: https://www.benzinga.com/sec/insider-trades/sitemap.xml',
   'sitemap: https://www.benzinga.com/sitemap_index.xml',
   'sitemap: https://www.benzinga.com/sitemap-benzinga.com/www/archive.xml',
   'sitemap: https://www.benzinga.com/sitemap-benzinga.com/www/latest.xml',
   'sitemap: https://www.benzinga.com/sitemap-benzinga.com/www/quotes.xml',
   'sitemap: https://www.benzinga.com/sitemap-benzinga.com/www/authors.xml'],
  None],
 ['https://creativecommons.org/robots.txt',
  'https://creativecommons.org/sitemap_index.xml',
  'https://creativecommons.org/rss',
  'https://creativecommons.org/rss2',
  ['sitemap: https://creativecommons.org/sitemap_index.xml'],
  None],
 ['https://www.socialmediatoday.com/robots.txt',
  None,
  None,
  None,
  ['allow: /google_news_sitemap.xml'],
  None],
 ['https://dailycoin.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://dailycoin.com/sitemap_index.xml',
   'sitemap: https://dailycoin.com/news-sitemap.xml'],
  None],
 ['https://venturebeat.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://venturebeat.com/news-sitemap.xml',
   '# sitemap archive',
   'sitemap: https://venturebeat.com/sitemap.xml'],
  None],
 ['https://www.thurrott.com/robots.txt',
  'https://www.thurrott.com/sitemap_index.xml',
  'https://www.thurrott.com/rss',
  'https://www.thurrott.com/rss2',
  ['sitemap: https://www.thurrott.com/sitemap_index.xml'],
  None],
 ['https://www.plagiarismtoday.com/robots.txt',
  'https://www.plagiarismtoday.com/sitemap_index.xml',
  'https://www.plagiarismtoday.com/rss',
  'https://www.plagiarismtoday.com/rss2',
  ['sitemap: https://www.plagiarismtoday.com/sitemap_index.xml\r'],
  None],
 ['http://www.china.org.cn/robots.txt', None, None, None, [], None],
 [None, None, None, None, None],
 ['https://www.rbc.ru/robots.txt',
  'https://www.rbc.ru/sitemap_index.xml',
  None,
  None,
  ['sitemap: https://www.rbc.ru/sitemap_index.xml'],
  None],
 ['https://www.fintechfutures.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.fintechfutures.com/sitemap_index.xml'],
  None],
 ['https://en.coin-turk.com/robots.txt',
  'https://en.coin-turk.com/sitemap_index.xml',
  'https://en.coin-turk.com/rss',
  'https://en.coin-turk.com/rss2',
  ['# xml sitemap & google news version 5.3.6 - https://status301.net/wordpress-plugins/xml-sitemap-feed/',
   'sitemap: https://en.coin-turk.com/sitemap.xml',
   'sitemap: https://en.coin-turk.com/sitemap-news.xml',
   'sitemap: https://en.coin-turk.com/sitemap_index.xml'],
  None],
 ['https://coinpedia.org/robots.txt',
  'https://coinpedia.org/sitemap_index.xml',
  'https://coinpedia.org/rss',
  'https://coinpedia.org/rss2',
  ['sitemap: https://coinpedia.org/news-sitemap.xml',
   'sitemap: https://coinpedia.org/sitemap_index.xml',
   'sitemap: https://events.coinpedia.org/sitemap.xml'],
  None],
 ['https://www.silicon.co.uk/robots.txt',
  'https://www.silicon.co.uk/sitemap_index.xml',
  'https://www.silicon.co.uk/rss',
  'https://www.silicon.co.uk/rss2',
  ['sitemap: https://www.silicon.co.uk/sitemap.xml',
   'sitemap: https://www.silicon.co.uk/sitemap-news.xml'],
  None],
 ['https://www.euractiv.com/robots.txt',
  None,
  'https://www.euractiv.com/rss',
  'https://www.euractiv.com/rss2',
  [],
  None],
 ['https://www.ciodive.com/robots.txt',
  None,
  None,
  None,
  ['allow: /google_news_sitemap.xml'],
  None],
 ['https://www.traffictechnologytoday.com/robots.txt',
  None,
  'https://www.traffictechnologytoday.com/rss',
  'https://www.traffictechnologytoday.com/rss2',
  ['sitemap: https://www.traffictechnologytoday.com/wp-sitemap.xml'],
  None],
 [None, None, None, None, None],
 ['https://www.theregister.com/robots.txt', None, None, None, [], None],
 ['https://www.dailysabah.com/robots.txt',
  None,
  'https://www.dailysabah.com/rss',
  None,
  ['sitemap:  https://www.dailysabah.com/sitemaps/index.xml'],
  None],
 [None, None, None, None, None],
 ['https://convergedigest.blogspot.com/robots.txt',
  None,
  None,
  None,
  ['# blogger sitemap created on sun, 05 jun 2022 04:28:40 gmt',
   '# sitemap built with https://www.labnol.org/blogger/sitemap',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=1&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=1001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=1501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=2001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=2501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=3001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=3501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=4001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=4501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=5001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=5501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=6001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=6501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=7001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=7501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=8001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=8501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=9001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=9501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=10001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=10501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=11001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=11501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=12001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=12501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=13001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=13501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=14001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=14501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=15001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=15501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=16001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=16501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=17001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=17501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=18001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=18501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=19001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=19501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=20001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=20501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=21001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=21501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=22001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=22501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=23001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=23501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=24001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=24501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=25001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=25501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=26001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=26501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=27001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=27501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=28001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=28501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=29001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=29501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=30001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=30501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=31001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=31501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=32001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=32501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=33001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=33501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=34001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=34501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=35001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=35501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=36001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=36501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=37001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=37501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=38001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=38501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=39001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=39501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=40001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=40501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=41001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=41501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=42001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=42501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=43001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=43501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=44001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=44501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=45001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=45501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=46001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=46501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=47001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=47501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=48001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=48501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=49001&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=49501&max-results=500',
   'sitemap: https://www.convergedigest.com/atom.xml?redirect=false&start-index=50001&max-results=500'],
  None],
 ['https://www.coe.int/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.coe.int/sitemap.xml'],
  None],
 [None, None, None, None, None],
 ['https://betanews.com/robots.txt',
  None,
  'https://betanews.com/rss',
  'https://betanews.com/rss2',
  [],
  None],
 [None,
  'https://www.baselinemag.com/sitemap_index.xml',
  'https://www.baselinemag.com/rss',
  'https://www.baselinemag.com/rss2',
  None],
 ['https://www.businesswire.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: http://www.businesswire.com/smaps/gn-bw/gn-bw.xml',
   'sitemap: http://www.businesswire.com/smaps/smaps-bw/smap-bw.xml',
   'sitemap: http://feed.businesswire.com/mrss/home/?rss=g1qfderjxkjcfvjywq=='],
  None],
 ['https://www.prnewswire.com/robots.txt',
  None,
  'https://www.prnewswire.com/rss',
  None,
  ['sitemap: https://www.prnewswire.com/sitemap.xml',
   'sitemap: https://www.prnewswire.com/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/es/sitemap.xml',
   'sitemap: https://www.prnewswire.com/es/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/sv/sitemap.xml',
   'sitemap: https://www.prnewswire.com/sv/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/ru/sitemap.xml',
   'sitemap: https://www.prnewswire.com/ru/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/sk/sitemap.xml',
   'sitemap: https://www.prnewswire.com/sk/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/pt/sitemap.xml',
   'sitemap: https://www.prnewswire.com/pt/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/pl/sitemap.xml',
   'sitemap: https://www.prnewswire.com/pl/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/nl/sitemap.xml',
   'sitemap: https://www.prnewswire.com/nl/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/it/sitemap.xml',
   'sitemap: https://www.prnewswire.com/it/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/de/sitemap.xml',
   'sitemap: https://www.prnewswire.com/de/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/fi/sitemap.xml',
   'sitemap: https://www.prnewswire.com/fi/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/da/sitemap.xml',
   'sitemap: https://www.prnewswire.com/da/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/cs/sitemap.xml',
   'sitemap: https://www.prnewswire.com/cs/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/fr/sitemap.xml',
   'sitemap: https://www.prnewswire.com/fr/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/no/sitemap.xml',
   'sitemap: https://www.prnewswire.com/no/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/ae/sitemap.xml',
   'sitemap: https://www.prnewswire.com/ae/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/ae/ar/sitemap.xml',
   'sitemap: https://www.prnewswire.com/ae/ar/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/il/sitemap.xml',
   'sitemap: https://www.prnewswire.com/il/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/in/sitemap.xml',
   'sitemap: https://www.prnewswire.com/in/sitemap-news.xml',
   'sitemap: https://www.prnewswire.com/apac/sitemap.xml',
   'sitemap: https://www.prnewswire.com/apac/sitemap-news.xml'],
  None],
 [None, None, None, None, None],
 ['https://thepaypers.com/robots.txt',
  'https://thepaypers.com/sitemap_index.xml',
  None,
  None,
  ['sitemap: https://thepaypers.com/sitemap.xml'],
  None],
 ['https://iapp.org/robots.txt',
  'https://iapp.org/sitemap_index.xml',
  'https://iapp.org/rss',
  'https://iapp.org/rss2',
  ['sitemap: https://iapp.org/sitemap.xml'],
  None],
 ['https://c.newsnow.co.uk/robots.txt', None, None, None, [], None],
 ['https://www.wgem.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.wgem.com/arc/outboundfeeds/sitemap-index/?outputtype=xml',
   'sitemap: https://www.wgem.com/arc/outboundfeeds/news-sitemap-index/category/news/?outputtype=xml',
   'sitemap: https://www.wgem.com/arc/outboundfeeds/video-sitemap/?outputtype=xml',
   'sitemap: https://www.wgem.com/arc/outboundfeeds/sitemap-section-index/?outputtype=xml'],
  None],
 ['https://decrypt.co/robots.txt',
  'https://decrypt.co/sitemap_index.xml',
  'https://decrypt.co/rss',
  None,
  ['sitemap: https://decrypt.co/sitemap_index.xml',
   'sitemap: https://decrypt.co/es/sitemap_index.xml',
   'sitemap: https://decrypt.co/fr/sitemap_index.xml'],
  None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 ['https://paymentexpert.com/robots.txt',
  None,
  None,
  None,
  ['allow: /sitemap_index.xml',
   'allow: /sitemap_index.xml',
   'sitemap: https://paymentexpert.com/sitemap_index.xml'],
  None],
 [None, None, None, None, None],
 ['https://bitcoinworld.co.in/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://bitcoinworld.co.in/sitemap_index.xml\r'],
  None],
 [None, None, None, None, None],
 ['https://www.thestandard.com.hk/robots.txt', None, None, None, [], None],
 [None, None, None, None, None],
 ['https://u.today/robots.txt',
  None,
  'https://u.today/rss',
  'https://u.today/rss2',
  ['sitemap: https://u.today/googlenews',
   'sitemap: https://u.today/sitemaponeday',
   'sitemap: https://u.today/sitemap.xml'],
  None],
 ['https://www.bangkokpost.com/robots.txt',
  'https://www.bangkokpost.com/sitemap_index.xml',
  'https://www.bangkokpost.com/rss',
  None,
  ['sitemap: https://www.bangkokpost.com/sitemap.xml',
   'sitemap: https://www.bangkokpost.com/sitemap_news.xml'],
  None],
 ['https://www.mishcon.com/robots.txt',
  None,
  'https://www.mishcon.com/rss',
  None,
  ['sitemap: https://www.mishcon.com/google_sitemap.xml\r'],
  None],
 ['https://www.gulf-times.com/robots.txt',
  None,
  'https://www.gulf-times.com/rss',
  None,
  [],
  None],
 ['https://www.imf.org/robots.txt',
  'https://www.imf.org/sitemap_index.xml',
  'https://www.imf.org/rss',
  'https://www.imf.org/rss2',
  [],
  None],
 ['https://www.coindesk.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.coindesk.com/arc/outboundfeeds/sitemap-index/?outputtype=xml',
   'sitemap: https://www.coindesk.com/arc/outboundfeeds/news-sitemap-index/?outputtype=xml',
   'sitemap: https://www.coindesk.com/arc/outboundfeeds/consensus-articles-sitemap-index/?_website=coindesk',
   'sitemap: https://www.coindesk.com/arc/outboundfeeds/news-sitemap-index-es/',
   'sitemap: https://www.coindesk.com/arc/outboundfeeds/video-sitemap/'],
  None],
 [None, None, None, None, None],
 ['https://crypto.news/robots.txt',
  'https://crypto.news/sitemap_index.xml',
  'https://crypto.news/rss',
  'https://crypto.news/rss2',
  ['#add sitemap',
   'sitemap: https://crypto.news/sitemap_index.xml',
   'sitemap: https://crypto.news/news-sitemap.xml'],
  None],
 ['https://www.herald.co.zw/robots.txt',
  None,
  'https://www.herald.co.zw/rss',
  'https://www.herald.co.zw/rss2',
  [],
  None],
 ['http://en.people.cn/robots.txt',
  'http://en.people.cn/sitemap_index.xml',
  None,
  None,
  ['sitemap: http://en.people.cn/sitemap_index.xml'],
  None],
 ['https://www.atmmarketplace.com/robots.txt',
  None,
  'https://www.atmmarketplace.com/rss',
  None,
  ['user-agent: a1 sitemap generator', 'user-agent: ajsitemap'],
  None],
 ['https://news.bloomberglaw.com/robots.txt',
  'https://news.bloomberglaw.com/sitemap_index.xml',
  'https://news.bloomberglaw.com/rss',
  'https://news.bloomberglaw.com/rss2',
  [],
  None],
 ['https://www.dailymail.co.uk/robots.txt',
  None,
  None,
  None,
  ['# sitemap files',
   'sitemap: https://www.dailymail.co.uk/google-news-sitemap.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-channels.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-columnist.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-topics.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-videos-year~2021.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-facts-year~2021.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-articles-year~2021.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-videos-year~2022.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-articles-year~2022.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-facts-year~2022.xml',
   'sitemap: https://www.dailymail.co.uk/best-buys/sitemap.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-videos-year~2023.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-articles-year~2023.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-facts-year~2023.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-videos-year~2024.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-articles-year~2024.xml',
   'sitemap: https://www.dailymail.co.uk/sitemap-authors.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://www.ethnews.com/robots.txt',
  'https://www.ethnews.com/sitemap_index.xml',
  'https://www.ethnews.com/rss',
  'https://www.ethnews.com/rss2',
  ['sitemap: https://www.ethnews.com/sitemap_index.xml'],
  None],
 ['https://www.businesspost.ie/robots.txt',
  'https://www.businesspost.ie/sitemap_index.xml',
  'https://www.businesspost.ie/rss',
  'https://www.businesspost.ie/rss2',
  [],
  None],
 ['https://financialservices.house.gov/robots.txt',
  None,
  None,
  None,
  [],
  None],
 ['https://www.financemagnates.com/robots.txt',
  'https://www.financemagnates.com/sitemap_index.xml',
  None,
  None,
  ['sitemap: https://www.financemagnates.com/sitemap_index.xml',
   'sitemap: https://www.financemagnates.com/page-sitemap.xml',
   'sitemap: https://www.financemagnates.com/category-sitemap.xml',
   'sitemap: https://www.financemagnates.com/product-sitemap.xml',
   'sitemap: https://www.financemagnates.com/news-sitemap.xml',
   'sitemap: https://www.financemagnates.com/author-sitemap.xml',
   'sitemap: https://www.financemagnates.com/term-sitemap.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap1.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap2.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap3.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap4.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap5.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap6.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap7.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap8.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap9.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap10.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap11.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap12.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap13.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap14.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap15.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap16.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap17.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap18.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap19.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap20.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap21.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap22.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap23.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap24.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap25.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap26.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap27.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap28.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap29.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap30.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap31.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap32.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap33.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap34.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap35.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap36.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap37.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap38.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap39.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap40.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap41.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap42.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap43.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap44.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap45.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap46.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap47.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap48.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap49.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap50.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap51.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap52.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap53.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap54.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap55.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap56.xml',
   'sitemap: https://www.financemagnates.com/post-sitemap57.xml'],
  None],
 ['https://coinxposure.com/robots.txt',
  'https://coinxposure.com/sitemap_index.xml',
  'https://coinxposure.com/rss',
  'https://coinxposure.com/rss2',
  ['sitemap: https://coinxposure.com/sitemap_index.xml'],
  None],
 ['https://www.easa.europa.eu/robots.txt',
  None,
  'https://www.easa.europa.eu/rss',
  None,
  [],
  None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 ['https://www.ledgerinsights.com/robots.txt',
  'https://www.ledgerinsights.com/sitemap_index.xml',
  'https://www.ledgerinsights.com/rss',
  'https://www.ledgerinsights.com/rss2',
  [],
  None],
 ['https://www.postonline.co.uk/robots.txt', None, None, None, [], None],
 [None, None, None, None, None],
 ['https://www.geo.tv/robots.txt',
  'https://www.geo.tv/sitemap_index.xml',
  'https://www.geo.tv/rss',
  'https://www.geo.tv/rss2',
  ['sitemap: https://www.geo.tv/assets/uploads/sitemap.xml\r',
   'sitemap: https://www.geo.tv/assets/uploads/google_news_latest.xml\r',
   'sitemap: https://www.geo.tv/assets/uploads/google_embed_videos.xml'],
  None],
 ['https://www.budapesttimes.hu/robots.txt',
  'https://www.budapesttimes.hu/sitemap_index.xml',
  'https://www.budapesttimes.hu/rss',
  'https://www.budapesttimes.hu/rss2',
  ['sitemap: https://www.budapesttimes.hu/sitemap_index.xml',
   'sitemap: https://www.budapesttimes.hu/post-sitemap.xml',
   'sitemap: https://www.budapesttimes.hu/page-sitemap.xml',
   'sitemap: https://www.budapesttimes.hu/category-sitemap.xml'],
  None],
 ['https://financefeeds.com/robots.txt',
  'https://financefeeds.com/sitemap_index.xml',
  'https://financefeeds.com/rss',
  'https://financefeeds.com/rss2',
  ['sitemap: https://financefeeds.com/sitemap_index.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://www.scmp.com/robots.txt',
  None,
  'https://www.scmp.com/rss',
  None,
  ['# sitemap',
   'sitemap: https://www.scmp.com/sitemap.xml',
   'sitemap: https://www.scmp.com/sitemap_explained.xml',
   'sitemap: https://www.scmp.com/sitemap_podcasts.xml',
   'sitemap: https://www.scmp.com/sitemap_announcements.xml',
   'sitemap: https://www.scmp.com/sitemap_infographics.xml',
   'sitemap: https://www.scmp.com/sitemap_news.xml',
   'sitemap: https://www.scmp.com/sitemap_economy.xml',
   'sitemap: https://www.scmp.com/sitemap_business.xml',
   'sitemap: https://www.scmp.com/sitemap_comment.xml',
   'sitemap: https://www.scmp.com/sitemap_tech.xml',
   'sitemap: https://www.scmp.com/sitemap_lifestyle.xml',
   'sitemap: https://www.scmp.com/sitemap_culture.xml',
   'sitemap: https://www.scmp.com/sitemap_sport.xml',
   'sitemap: https://www.scmp.com/sitemap_property.xml',
   'sitemap: https://www.scmp.com/sitemap_photos.xml',
   'sitemap: https://www.scmp.com/sitemap_video.xml',
   'sitemap: https://www.scmp.com/sitemap_destination_macau.xml',
   'sitemap: https://www.scmp.com/sitemap_magazines.xml',
   'sitemap: https://www.scmp.com/sitemap_this_week_in_asia.xml',
   'sitemap: https://www.scmp.com/sitemap_directories.xml',
   'sitemap: https://www.scmp.com/sitemap_weather.xml',
   'sitemap: https://www.scmp.com/sitemap_about_us.xml',
   'sitemap: https://www.scmp.com/sitemap_lists.xml',
   'sitemap: https://www.scmp.com/sitemap_special_reports.xml',
   'sitemap: https://www.scmp.com/sitemap_country_reports.xml',
   'sitemap: https://www.scmp.com/sitemap_video_comments.xml',
   'sitemap: https://www.scmp.com/sitemap_video_scmp_originals.xml',
   'sitemap: https://www.scmp.com/sitemap_video_hong_kong.xml',
   'sitemap: https://www.scmp.com/sitemap_video_china.xml',
   'sitemap: https://www.scmp.com/sitemap_video_asia.xml',
   'sitemap: https://www.scmp.com/sitemap_video_world.xml',
   'sitemap: https://www.scmp.com/sitemap_video_business.xml',
   'sitemap: https://www.scmp.com/sitemap_video_arts_culture.xml',
   'sitemap: https://www.scmp.com/sitemap_video_technology.xml',
   'sitemap: https://www.scmp.com/sitemap_video_lifestyle.xml',
   'sitemap: https://www.scmp.com/sitemap_video_sport.xml',
   'sitemap: https://www.scmp.com/sitemap_video_offbeat.xml',
   'sitemap: https://www.scmp.com/sitemap_video_style.xml',
   'sitemap: https://www.scmp.com/sitemap_video_post_mag.xml',
   'sitemap: https://www.scmp.com/sitemap_video_presented.xml',
   'sitemap: https://www.scmp.com/sitemap_article.xml',
   'sitemap: https://www.scmp.com/sitemap_gallery.xml',
   'sitemap: https://www.scmp.com/sitemap_poll.xml',
   'sitemap: https://www.scmp.com/sitemap_promotion.xml',
   'sitemap: https://www.scmp.com/sitemap_webform.xml',
   'sitemap: https://www.scmp.com/sitemap_video_format.xml',
   'sitemap: https://www.scmp.com/sitemap_sections.xml',
   'sitemap: https://www.scmp.com/sitemap_topics.xml',
   'sitemap: https://www.scmp.com/sitemap_authors.xml',
   'sitemap: https://www.scmp.com/sitemap_archive.xml',
   'sitemap: https://www.scmp.com/sitemap_abacus.xml',
   'sitemap: https://www.scmp.com/sitemap_recipe.xml',
   'sitemap: https://www.scmp.com/sitemap_better_life.xml',
   'sitemap: https://www.scmp.com/sitemap_podcast.xml'],
  None],
 ['https://futurism.com/robots.txt',
  'https://futurism.com/sitemap_index.xml',
  None,
  None,
  ['sitemap: https://futurism.com/sitemap_index.xml\r',
   'sitemap: https://futurism.com/news-sitemap.xml'],
  None],
 ['https://www.channelnewsasia.com/robots.txt',
  None,
  'https://www.channelnewsasia.com/rss',
  None,
  ['allow: /api/v1/sitemap-video-feed\r',
   'allow: /api/v1/sitemap-news-feed\r',
   'allow: /api/v1/sitemap-image-feed\r',
   'sitemap: https://www.channelnewsasia.com/api/v1/sitemap-news-feed?_format=xml\r',
   'sitemap: https://www.channelnewsasia.com/api/v1/sitemap-video-feed?_format=xml\r',
   'sitemap: https://www.channelnewsasia.com/api/v1/sitemap-image-feed?_format=xml\r',
   'sitemap: https://www.channelnewsasia.com/api/v1/google-audio-news-feed'],
  None],
 [None, None, None, None, None],
 ['https://bits.media/robots.txt',
  'https://bits.media/sitemap_index.xml',
  None,
  'https://bits.media/rss2',
  ['sitemap: https://bits.media/sitemap.php'],
  None],
 ['https://timesofindia.indiatimes.com/robots.txt',
  None,
  None,
  None,
  [],
  None],
 ['https://www.info.gov.hk/robots.txt',
  None,
  'https://www.info.gov.hk/rss',
  None,
  [],
  None],
 [None, None, 'https://blockworks.co/rss', None, None],
 ['https://mashable.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://mashable.com/sitemap-index.xml',
   'sitemap: https://mashable.com/sitemap-news-0.xml'],
  None],
 ['https://www.centralbanking.com/robots.txt', None, None, None, [], None],
 ['https://www.al-monitor.com/robots.txt',
  None,
  'https://www.al-monitor.com/rss',
  None,
  [],
  None],
 ['https://www.irishexaminer.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.irishexaminer.com/sitemap-index/41-google_news.xml\r',
   'sitemap: https://www.irishexaminer.com/sitemap-index/44-google_sitemap.xml\r',
   'sitemap: https://www.irishexaminer.com/sitemap-index/227-google_channel_sitemap.xml\r'],
  None],
 ['https://www.cbc.ca/robots.txt',
  None,
  'https://www.cbc.ca/rss',
  None,
  [],
  None],
 ['https://sdg.iisd.org/robots.txt',
  None,
  'https://sdg.iisd.org/rss',
  'https://sdg.iisd.org/rss2',
  [],
  None],
 ['https://www.forexlive.com/robots.txt',
  'https://www.forexlive.com/sitemap_index.xml',
  'https://www.forexlive.com/rss',
  None,
  ['sitemap: https://www.forexlive.com/sitemap_index.xml',
   'sitemap: https://www.forexlive.com/pages-sitemap.xml',
   'sitemap: https://www.forexlive.com/categories-sitemap.xml',
   'sitemap: https://www.forexlive.com/news-sitemap.xml',
   'sitemap: https://www.forexlive.com/authors-sitemap.xml',
   'sitemap: https://www.forexlive.com/terms-sitemap.xml',
   'sitemap: https://www.forexlive.com/directory-categories-sitemap.xml',
   'sitemap: https://www.forexlive.com/companies-sitemap.xml',
   'sitemap: https://www.forexlive.com/post-sitemap.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-1.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-2.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-3.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-4.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-5.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-6.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-7.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-8.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-9.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-10.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-11.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-12.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-13.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-14.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-15.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-16.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-17.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-18.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-19.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-20.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-21.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-22.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-23.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-24.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-25.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-26.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-27.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-28.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-29.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-30.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-31.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-32.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-33.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-34.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-35.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-36.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-37.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-38.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-39.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-40.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-41.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-42.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-43.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-44.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-45.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-46.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-47.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-48.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-49.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-50.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-51.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-52.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-53.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-54.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-55.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-56.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-57.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-58.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-59.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-60.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-61.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-62.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-63.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-64.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-65.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-66.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-67.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-68.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-69.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-70.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-71.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-72.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-73.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-74.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-75.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-76.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-77.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-78.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-79.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-80.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-81.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-82.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-83.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-84.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-85.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-86.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-87.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-88.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-89.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-90.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-91.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-92.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-93.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-94.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-95.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-96.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-97.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-98.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-99.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-100.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-101.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-102.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-103.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-104.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-105.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-106.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-107.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-108.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-109.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-110.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-111.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-112.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-113.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-114.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-115.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-116.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-117.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-118.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-119.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-120.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-121.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-122.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-123.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-124.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-125.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-126.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-127.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-128.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-129.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-130.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-131.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-132.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-133.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-134.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-135.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-136.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-137.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-138.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-139.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-140.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-141.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-142.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-143.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-144.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-145.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-146.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-147.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-148.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-149.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-150.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-151.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-152.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-153.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-154.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-155.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-156.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-157.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-158.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-159.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-160.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-161.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-162.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-163.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-164.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-165.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-166.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-167.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-168.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-169.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-170.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-171.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-172.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-173.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-174.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-175.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-176.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-177.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-178.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-179.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-180.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-181.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-182.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-183.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-184.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-185.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-186.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-187.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-188.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-189.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-190.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-191.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-192.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-193.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-194.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-195.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-196.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-197.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-198.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-199.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-200.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-201.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-202.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-203.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-204.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-205.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-206.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-207.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-208.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-209.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-210.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-211.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-212.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-213.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-214.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-215.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-216.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-217.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-218.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-219.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-220.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-221.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-222.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-223.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-224.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-225.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-226.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-227.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-228.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-229.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-230.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-231.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-232.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-233.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-234.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-235.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-236.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-237.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-238.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-239.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-240.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-241.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-242.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-243.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-244.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-245.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-246.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-247.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-248.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-249.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-250.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-251.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-252.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-253.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-254.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-255.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-256.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-257.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-258.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-259.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-260.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-261.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-262.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-263.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-264.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-265.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-266.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-267.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-268.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-269.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-270.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-271.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-272.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-273.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-274.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-275.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-276.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-277.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-278.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-279.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-280.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-281.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-282.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-283.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-284.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-285.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-286.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-287.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-288.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-289.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-290.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-291.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-292.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-293.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-294.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-295.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-296.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-297.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-298.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-299.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-300.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-301.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-302.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-303.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-304.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-305.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-306.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-307.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-308.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-309.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-310.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-311.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-312.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-313.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-314.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-315.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-316.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-317.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-318.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-319.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-320.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-321.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-322.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-323.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-324.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-325.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-326.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-327.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-328.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-329.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-330.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-331.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-332.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-333.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-334.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-335.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-336.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-337.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-338.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-339.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-340.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-341.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-342.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-343.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-344.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-345.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-346.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-347.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-348.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-349.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-350.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-351.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-352.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-353.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-354.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-355.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-356.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-357.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-358.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-359.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-360.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-361.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-362.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-363.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-364.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-365.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-366.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-367.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-368.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-369.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-370.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-371.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-372.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-373.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-374.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-375.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-376.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-377.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-378.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-379.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-380.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-381.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-382.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-383.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-384.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-385.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-386.xml',
   'sitemap: https://www.forexlive.com/post-sitemap-387.xml'],
  None],
 ['https://www.reuters.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.reuters.com/arc/outboundfeeds/sitemap-index/?outputtype=xml',
   'sitemap: https://www.reuters.com/arc/outboundfeeds/news-sitemap-index/?outputtype=xml',
   'sitemap: https://www.reuters.com/sitemap_video_index.xml',
   'sitemap: https://www.reuters.com/plus/sitemap-index.xml',
   'sitemap: https://www.reuters.com/arc/outboundfeeds/sitemap-plj-index/?outputtype=xml',
   'sitemap: https://www.reuters.com/graphics/sitemap.xml'],
  None],
 ['https://www.thehindu.com/robots.txt',
  None,
  'https://www.thehindu.com/rss',
  'https://www.thehindu.com/rss2',
  ['# block picture sitemap because urls are noindex therein',
   'disallow: /sitemap/archive/picture/',
   'disallow: /sitemap/archive*',
   'disallow: /sitemap/',
   'allow: /sitemap/$',
   'sitemap: https://www.thehindu.com/feeder/default.rss',
   'sitemap: https://www.thehindu.com/coupons/sitemap.xml'],
  None],
 ['https://www.ndtv.com/robots.txt',
  None,
  'https://www.ndtv.com/rss',
  None,
  ['sitemap: https://www.ndtv.com/sitemap.xml\r',
   'sitemap: https://www.ndtv.com/sitemap/google-news-sitemap\r',
   'sitemap: https://www.ndtv.com/sitemap.xml?years=2023\r',
   'sitemap: https://www.ndtv.com/entertainment/sitemap-2023\r',
   'sitemap: https://www.ndtv.com/entertainment/sitemap.xml?years=2023\r'],
  None],
 [None, None, None, None, None],
 ['https://timesofmalta.com/robots.txt',
  'https://timesofmalta.com/sitemap_index.xml',
  'https://timesofmalta.com/rss',
  None,
  ['sitemap: https://timesofmalta.com/sitemap_index.xml'],
  None],
 ['https://www.courthousenews.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.courthousenews.com/wp-sitemap.xml'],
  None],
 ['https://www.upi.com/robots.txt',
  'error',
  'https://www.upi.com/rss',
  None,
  [],
  None],
 ['https://coinpaper.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://coinpaper.com/sitemap.xml'],
  None],
 ['https://www.interpol.int/robots.txt', None, None, None, [], None],
 ['https://www.finextra.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.finextra.com/sitemaps/index.aspx\r',
   'sitemap: https://www.finextra.com/sitemaps/sitemap.xml\r',
   'sitemap: https://www.finextra.com/sitemaps/headlines.aspx\r',
   'sitemap: https://www.finextra.com/sitemaps/headlinesgooglenews.aspx\r',
   'sitemap: https://www.finextra.com/rss/headlines.aspx\r',
   'sitemap: https://www.finextra.com/rss/blogs.aspx\r',
   'sitemap: https://www.finextra.com/rss/jobs.aspx\r',
   'sitemap: https://www.finextra.com/rss/events.aspx\r',
   'allow: /sitemaps/\r',
   'allow: /sitemaps/\r'],
  None],
 ['https://dcnnmagazine.com/robots.txt',
  'https://dcnnmagazine.com/sitemap_index.xml',
  None,
  None,
  ['sitemap: https://dcnnmagazine.com/sitemap_index.xml'],
  None],
 ['https://www.biometricupdate.com/robots.txt',
  'https://www.biometricupdate.com/sitemap_index.xml',
  'https://www.biometricupdate.com/rss',
  'https://www.biometricupdate.com/rss2',
  [],
  None],
 ['https://www.pymnts.com/robots.txt',
  'error',
  'https://www.pymnts.com/rss',
  'https://www.pymnts.com/rss2',
  ['sitemap: https://www.pymnts.com/sitemap_index.xml'],
  None],
 [None, None, 'https://www.nation.com.pk/rss', None, None],
 ['https://www.rte.ie/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.rte.ie/sitemap.xml\r'],
  None],
 ['https://www.bostonglobe.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.bostonglobe.com/arc/outboundfeeds/sitemap/?outputtype=xml',
   'sitemap: https://www.bostonglobe.com/arc/outboundfeeds/news-sitemap/?outputtype=xml'],
  None],
 ['https://arstechnica.com/robots.txt',
  'https://arstechnica.com/sitemap_index.xml',
  'https://arstechnica.com/rss',
  'https://arstechnica.com/rss2',
  ['sitemap: https://arstechnica.com/sitemap.xml'],
  None],
 ['https://forklog.com/robots.txt',
  None,
  'https://forklog.com/rss',
  None,
  ['sitemap: https://forklog.com/sitemap.xml\r'],
  None],
 ['https://www.tuko.co.ke/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.tuko.co.ke/tuko/sitemap/www/sitemap.xml',
   'sitemap: https://www.tuko.co.ke/tuko/sitemap/www/news.xml',
   'sitemap: https://www.tuko.co.ke/tuko/sitemap/www/category-sitemap.xml',
   'sitemap: https://www.tuko.co.ke/tuko/sitemap/www/tag-sitemap.xml',
   'sitemap: https://www.tuko.co.ke/tuko/sitemap/www/author-sitemap.xml',
   'sitemap: https://www.tuko.co.ke/tuko/sitemap/www/expert-sitemap.xml',
   'sitemap: https://www.tuko.co.ke/tuko/sitemap/www/static-sitemap.xml'],
  None],
 ['https://www.techspot.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.techspot.com/sitemap/sitemap.xml',
   'sitemap: https://www.techspot.com/sitemap/news_today.xml'],
  None],
 [None, None, None, None, None],
 ['https://www.forbes.com/robots.txt',
  'https://www.forbes.com/sitemap_index.xml',
  None,
  None,
  ['sitemap: https://www.forbes.com/news_sitemap.xml',
   'sitemap: https://www.forbes.com/video_sitemap.xml',
   'sitemap: https://www.forbes.com/coupons/sitemap.xml'],
  None],
 ['https://www.globaltimes.cn/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.globaltimes.cn/sitemap.xml'],
  None],
 ['https://www.jdsupra.com/robots.txt',
  'https://www.jdsupra.com/sitemap_index.xml',
  None,
  None,
  ['sitemap: http://www.jdsupra.com/sitemap_index.xml\r'],
  None],
 ['error',
  None,
  'https://www.aljazeera.com/rss',
  None,
  ['sitemap: https://www.aljazeera.com/sitemap.xml',
   'sitemap: https://www.aljazeera.com/sitemaps/article-archive.xml',
   'sitemap: https://www.aljazeera.com/sitemaps/article-new.xml',
   'sitemap: https://www.aljazeera.com/sitemaps/video-archive.xml',
   'sitemap: https://www.aljazeera.com/sitemaps/video-new.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://www.livemint.com/robots.txt',
  None,
  'https://www.livemint.com/rss',
  None,
  ['sitemap: https://www.livemint.com/sitemap/yesterday.xml',
   'sitemap: https://www.livemint.com/sitemap/today.xml',
   'sitemap: https://www.livemint.com/lm-section/sitemap.xml'],
  None],
 ['https://www.bis.org/robots.txt',
  None,
  'https://www.bis.org/rss',
  None,
  ['sitemap: https://www.bis.org/sitemap.xml'],
  None],
 ['https://bis.org/robots.txt',
  None,
  'https://bis.org/rss',
  None,
  ['sitemap: https://www.bis.org/sitemap.xml'],
  None],
 ['https://www.informationweek.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.informationweek.com/sitemap.xml',
   'sitemap: https://www.informationweek.com/generic-content.xml',
   'sitemap: https://www.informationweek.com/article-content-formats-index.xml',
   'sitemap: https://www.informationweek.com/googlenews.xml',
   'sitemap: https://www.informationweek.com/news-archive-index.xml',
   'sitemap: https://www.informationweek.com/contributors.xml',
   'sitemap: https://www.informationweek.com/podcast-archive-index.xml',
   'sitemap: https://www.informationweek.com/webinar-archive-index.xml',
   'sitemap: https://www.informationweek.com/document-archive-index.xml',
   'sitemap: https://www.informationweek.com/event-archive-index.xml',
   'sitemap: https://www.informationweek.com/videos-archive-index.xml',
   'sitemap: https://www.informationweek.com/image-archive-index.xml',
   'sitemap: https://www.informationweek.com/sitemap-index.xml'],
  None],
 ['https://www.iflr.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.iflr.com/sitemap.xml'],
  None],
 ['https://www.techrepublic.com/robots.txt',
  'https://www.techrepublic.com/sitemap_index.xml',
  'https://www.techrepublic.com/rss',
  None,
  ['sitemap: https://www.techrepublic.com/sitemap_index.xml'],
  None],
 ['https://www.computing.co.uk/robots.txt',
  'https://www.computing.co.uk/sitemap_index.xml',
  None,
  None,
  ['# sitemap declarations',
   'sitemap: https://www.computing.co.uk/sitemap_index.xml',
   'sitemap: https://www.computing.co.uk/news-sitemap.xml',
   'sitemap: https://www.computing.co.uk/videositemap.xml',
   'sitemap: https://www.computing.co.uk/sitemap_index.xml',
   'sitemap: https://www.computing.co.uk/news-sitemap.xml',
   'sitemap: https://www.computing.co.uk/videositemap.xml',
   'sitemap: https://www.computing.co.uk/sitemap_index.xml',
   'sitemap: https://www.computing.co.uk/news-sitemap.xml',
   'sitemap: https://www.computing.co.uk/videositemap.xml',
   'sitemap: https://www.computing.co.uk/sitemap_index.xml',
   'sitemap: https://www.computing.co.uk/news-sitemap.xml',
   'sitemap: https://www.computing.co.uk/videositemap.xml'],
  None],
 ['https://en.vietnamplus.vn/robots.txt',
  None,
  None,
  None,
  ['sitemap: http://en.vietnamplus.vn/sitemap.xml\r',
   'sitemap: http://es.vietnamplus.vn/sitemap.xml\r',
   'sitemap: http://fr.vietnamplus.vn/sitemap.xml\r',
   'sitemap: http://zh.vietnamplus.vn/sitemap.xml'],
  None],
 ['https://www.aa.com.tr/robots.txt', None, None, None, [], None],
 ['https://www.mckinsey.com/robots.txt',
  None,
  'https://www.mckinsey.com/rss',
  None,
  ['sitemap: https://www.mckinsey.com/sitemap.xml'],
  None],
 ['https://www.bloomberg.com/robots.txt',
  'https://www.bloomberg.com/sitemap_index.xml',
  'https://www.bloomberg.com/rss',
  'https://www.bloomberg.com/rss2',
  ['sitemap: https://www.bloomberg.com/sitemap.xml',
   'sitemap: https://www.bloomberg.com/feeds/sitemap_news.xml',
   'sitemap: https://www.bloomberg.com/feeds/bbiz/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/bpol/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/businessweek/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/citylab/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/green/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/technology/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/bbiz/sitemap_securities_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/bbiz/sitemap_profiles_company_index.xml',
   'sitemap: https://www.bloomberg.com/billionaires/sitemap.xml',
   'sitemap: https://www.bloomberg.com/feeds/bbiz/sitemap_news.xml',
   'sitemap: https://www.bloomberg.com/feeds/dynamic/private-company-index.xml',
   'sitemap: https://www.bloomberg.com/feeds/dynamic/person-index.xml',
   'sitemap: https://www.bloomberg.com/feeds/curated/feeds/graphics_news.xml',
   'sitemap: https://www.bloomberg.com/feeds/curated/feeds/graphics_sitemap.xml',
   'sitemap: https://www.bloomberg.com/feeds/equality/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/wealth/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/multimedia/sitemap.xml',
   'sitemap: https://www.bloomberg.com/feeds/curated/bbiz_sitemap.xml',
   'sitemap: https://www.bloomberg.com/feeds/pursuits/sitemap_index.xml',
   'sitemap: https://www.bloomberg.com/feeds/quicktake/sitemap_index.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://yen.com.gh/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://yen.com.gh/yen/sitemap/sitemap.xml',
   'sitemap: https://yen.com.gh/yen/sitemap/news.xml',
   'sitemap: https://yen.com.gh/yen/sitemap/category-sitemap.xml',
   'sitemap: https://yen.com.gh/yen/sitemap/tag-sitemap.xml',
   'sitemap: https://yen.com.gh/yen/sitemap/author-sitemap.xml',
   'sitemap: https://yen.com.gh/yen/sitemap/expert-sitemap.xml',
   'sitemap: https://yen.com.gh/yen/sitemap/static-sitemap.xml'],
  None],
 [None, None, None, None, None],
 ['https://www.fsb.org/robots.txt',
  None,
  'https://www.fsb.org/rss',
  'https://www.fsb.org/rss2',
  [],
  None],
 [None, None, None, None, None],
 ['https://www.iosco.org/robots.txt', None, None, None, [], None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 ['https://techinformed.com/robots.txt',
  'https://techinformed.com/sitemap_index.xml',
  'https://techinformed.com/rss',
  'https://techinformed.com/rss2',
  ['sitemap: https://techinformed.com/sitemap.xml',
   'sitemap: https://techinformed.com/news-sitemap.xml',
   'sitemap: https://techinformed.com/sitemap_index.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['https://cryptobriefing.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://cryptobriefing.com/sitemap_index.xml'],
  None],
 ['https://www.digitaljournal.com/robots.txt',
  'error',
  'https://www.digitaljournal.com/rss',
  'error',
  [],
  None],
 ['https://tech.hindustantimes.com/robots.txt',
  None,
  'https://tech.hindustantimes.com/rss',
  None,
  ['sitemap: https://tech.hindustantimes.com/sitemap-index.xml',
   'sitemap: https://tech.hindustantimes.com/news-sitemap.xml',
   'sitemap: https://tech.hindustantimes.com/section-sitemap.xml',
   'sitemap: https://tech.hindustantimes.com/photos.xml',
   'sitemap: https://tech.hindustantimes.com/sitemap-laptops-product.xml',
   'sitemap: https://tech.hindustantimes.com/sitemap-mobiles-product.xml',
   'sitemap: https://tech.hindustantimes.com/sitemap-tablets-product.xml'],
  None],
 ['https://www.investing.com/robots.txt',
  'https://www.investing.com/sitemap_index.xml',
  None,
  None,
  [],
  None],
 ['https://cryptodaily.co.uk/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://cryptodaily.co.uk/sitemap.xml',
   'sitemap: https://cryptodaily.co.uk/sitemaps/sitemap_categories.xml',
   'sitemap: https://cryptodaily.co.uk/sitemaps/sitemap_tags.xml',
   'sitemap: https://cryptodaily.co.uk/sitemaps/sitemap_pages.xml',
   'sitemap: https://cryptodaily.co.uk/sitemaps/sitemap_posts_1.xml'],
  None],
 ['https://www.deccanherald.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://www.deccanherald.com/news_sitemap.xml',
   'sitemap: https://www.deccanherald.com/sitemap.xml'],
  None],
 ['https://coingeek.com/robots.txt',
  'https://coingeek.com/sitemap_index.xml',
  'https://coingeek.com/rss',
  'https://coingeek.com/rss2',
  ['sitemap: https://coingeek.com/sitemap_index.xml'],
  None],
 ['error', 'error', 'error', 'error', 'error'],
 ['http://www.cbr.ru/robots.txt', None, None, None, [], None],
 ['https://www.uktech.news/robots.txt',
  'https://www.uktech.news/sitemap_index.xml',
  'https://www.uktech.news/rss',
  'https://www.uktech.news/rss2',
  [],
  None],
 ['https://www.computerweekly.com/robots.txt',
  None,
  'https://www.computerweekly.com/rss',
  None,
  ['sitemap: https://www.computerweekly.com/siteindex.xml\r',
   'sitemap: https://www.computerweekly.com/googlenews.xml\r',
   'sitemap: https://www.computerweekly.com/siteindexvideo.xml\r',
   'sitemap: https://www.computerweekly.com/de/siteindex.xml\r',
   'sitemap: https://www.computerweekly.com/de/googlenews.xml\r',
   'sitemap: https://www.computerweekly.com/de/siteindexvideo.xml\r',
   'sitemap: https://www.computerweekly.com/br/siteindex.xml\r',
   'sitemap: https://www.computerweekly.com/br/googlenews.xml\r',
   'sitemap: https://www.computerweekly.com/br/siteindexvideo.xml\r',
   'sitemap: https://www.computerweekly.com/es/siteindex.xml\r',
   'sitemap: https://www.computerweekly.com/es/googlenews.xml\r',
   'sitemap: https://www.computerweekly.com/es/siteindexvideo.xml\r',
   'sitemap: https://www.computerweekly.com/microscope/siteindex.xml\r',
   'sitemap: https://www.computerweekly.com/microscope/googlenews.xml\r',
   'sitemap: https://www.computerweekly.com/microscope/siteindexvideo.xml'],
  None],
 [None, None, None, None, None],
 ['https://economictimes.indiatimes.com/robots.txt',
  None,
  None,
  None,
  ['sitemap: https://economictimes.indiatimes.com/companylisting.cms ',
   'sitemap: https://economictimes.indiatimes.com/newssitemapindex.cms ',
   'sitemap: https://economictimes.indiatimes.com/etstatic/sitemaps/et/sitemap-index.xml ',
   'sitemap: https://economictimes.indiatimes.com/sitemapxml.cms ',
   'sitemap: https://economictimes.indiatimes.com/etstatic/sitemaps/etvideo/sitemap-index.xml',
   'sitemap: https://economictimes.indiatimes.com/sitemap/today',
   'sitemap: https://economictimes.indiatimes.com/sitemap/yesterday',
   'sitemap: https://economictimes.indiatimes.com/companylisting.cms ',
   'sitemap: https://economictimes.indiatimes.com/newssitemapindex.cms ',
   'sitemap: https://economictimes.indiatimes.com/etstatic/sitemaps/et/sitemap-index.xml ',
   'sitemap: https://economictimes.indiatimes.com/sitemapxml.cms ',
   'sitemap: https://economictimes.indiatimes.com/etstatic/sitemaps/etvideo/sitemap-index.xml',
   'sitemap: https://economictimes.indiatimes.com/sitemap/today',
   'sitemap: https://economictimes.indiatimes.com/sitemap/yesterday'],
  None],
 [None, None, None, None, None],
 ['https://blogs.law.ox.ac.uk/robots.txt', None, None, None, [], None],
 [None, None, None, None, None],
 ['https://www.theblock.co/robots.txt',
  None,
  'https://www.theblock.co/rss',
  'https://www.theblock.co/rss2',
  ['sitemap: https://www.theblock.co/sitemap_tbco_index.xml',
   'sitemap: https://www.theblock.co/sitemap_tbco_news.xml'],
  None],
 ['https://tribuneonlineng.com/robots.txt',
  'error',
  'https://tribuneonlineng.com/rss',
  'https://tribuneonlineng.com/rss2',
  ['sitemap: https://tribuneonlineng.com/sitemap_index.xml'],
  None]]