# links = [
#     'https://www.ecb.europa.eu/rss',
#     'https://www.govinfosecurity.com/rss',
#     'https://www.techradar.com/rss',
#     'https://www.the-star.co.ke/rss',
#     'https://kuwaittimes.com/rss',
#     'https://www.independent.ie/rss',
#     'https://uk.practicallaw.thomsonreuters.com/rss',
#     'https://www.gmanetwork.com/rss',
#     'https://www.laprensalatina.com/rss',
#     'https://creativecommons.org/rss',
#     'https://www.thurrott.com/rss',
#     'https://www.plagiarismtoday.com/rss',
#     'https://en.coin-turk.com/rss',
#     'https://coinpedia.org/rss',
#     'https://www.silicon.co.uk/rss',
#     'https://www.euractiv.com/rss',
#     'https://www.traffictechnologytoday.com/rss',
#     'https://www.dailysabah.com/rss',
#     'https://betanews.com/rss',
#     'https://www.baselinemag.com/rss',
#     'https://www.prnewswire.com/rss',
#     'https://iapp.org/rss',
#     'https://decrypt.co/rss',
#     'https://u.today/rss',
#     'https://www.bangkokpost.com/rss',
#     'https://www.mishcon.com/rss',
#     'https://www.gulf-times.com/rss',
#     'https://www.imf.org/rss',
#     'https://crypto.news/rss',
#     'https://www.herald.co.zw/rss',
#     'https://www.atmmarketplace.com/rss',
#     'https://news.bloomberglaw.com/rss',
#     'https://www.ethnews.com/rss',
#     'https://www.businesspost.ie/rss',
#     'https://coinxposure.com/rss',
#     'https://www.easa.europa.eu/rss',
#     'https://www.ledgerinsights.com/rss',
#     'https://www.budapesttimes.hu/rss',
#     'https://financefeeds.com/rss',
#     'https://www.scmp.com/rss',
#     'https://www.channelnewsasia.com/rss',
#     'https://www.info.gov.hk/rss',
#     'https://blockworks.co/rss',
#     'https://www.al-monitor.com/rss',
#     'https://www.cbc.ca/rss',
#     'https://sdg.iisd.org/rss',
#     'https://www.forexlive.com/rss',
#     'https://www.thehindu.com/feeder/default.rss',
#     'https://www.thehindu.com/rss',
#     'https://timesofmalta.com/rss',
#     'https://www.upi.com/rss',
#     'https://www.biometricupdate.com/rss',
#     'https://www.pymnts.com/rss',
#     'https://www.nation.com.pk/rss',
#     'https://arstechnica.com/rss',
#     'https://forklog.com/rss',
#     'https://www.aljazeera.com/rss',
#     'https://www.livemint.com/rss',
#     'https://www.bis.org/rss',
#     'https://bis.org/rss',
#     'https://www.techrepublic.com/rss',
#     'https://www.mckinsey.com/rss',
#     'https://www.bloomberg.com/rss',
#     'https://www.fsb.org/rss',
#     'https://techinformed.com/rss',
#     'https://www.digitaljournal.com/rss',
#     'https://tech.hindustantimes.com/rss',
#     'https://coingeek.com/rss',
#     'https://www.uktech.news/rss',
#     'https://www.computerweekly.com/rss',
#     'https://www.theblock.co/rss',
#     'https://tribuneonlineng.com/rss',
# ]
# links = ["https://www.ecb.europa.eu/rss/press.html",
# "https://www.ecb.europa.eu/rss/blog.html",
# "https://www.ecb.europa.eu/rss/statpress.html",
# "https://www.ecb.europa.eu/rss/pub.html",
# "https://www.ecb.europa.eu/rss/wppub.html",
# "https://www.ecb.europa.eu/rss/operations.html",
# "https://www.ecb.europa.eu/rss/procurements.html",
# "https://www.ecb.europa.eu/rss/yc.html",
# "https://www.ecb.europa.eu/rss/rbu.html",
# "https://www.govinfosecurity.com/rss",
# "https://www.techradar.com/rss",
# "https://www.the-star.co.ke/rss",
# "https://kuwaittimes.com/rssFeed/0",
# "https://kuwaittimes.com/rssFeed/10",
# "https://kuwaittimes.com/rssFeed/1",
# "https://kuwaittimes.com/rssFeed/2",
# "https://kuwaittimes.com/rssFeed/3",
# "https://kuwaittimes.com/rssFeed/4",
# "https://kuwaittimes.com/rssFeed/5",
# "https://kuwaittimes.com/rssFeed/6",
# "https://kuwaittimes.com/rssFeed/7",
# "https://kuwaittimes.com/rssFeed/8",
# "https://kuwaittimes.com/rssFeed/9",
# "https://kuwaittimes.com/rssFeed/11",
# "https://kuwaittimes.com/rssFeed/12",
# "https://kuwaittimes.com/rssFeed/13",
# "https://kuwaittimes.com/rssFeed/14",
# "https://kuwaittimes.com/rssFeed/15",
# "https://kuwaittimes.com/rssFeed/23",
# "https://kuwaittimes.com/rssFeed/18",
# "https://kuwaittimes.com/rssFeed/17",
# "https://kuwaittimes.com/rssFeed/20",
# "https://www.laprensalatina.com/feed/",
# "https://creativecommons.org/feed/",
# "https://www.thurrott.com/feed",
# "https://www.plagiarismtoday.com/feed/",
# "https://coinpedia.org/feed/",
# "https://www.silicon.co.uk/feed",
# "https://www.euractiv.com/feed/",
# "https://www.traffictechnologytoday.com/feed",
# "https://www.dailysabah.com/rssFeed/10/1",
# "https://www.dailysabah.com/rssFeed/10/2",
# "https://www.dailysabah.com/rssFeed/10/3",
# "https://www.dailysabah.com/rssFeed/10/4",
# "https://www.dailysabah.com/rssFeed/10/5",
# "https://www.dailysabah.com/rssFeed/10/6",
# "https://www.dailysabah.com/rssFeed/11/7",
# "https://www.dailysabah.com/rssFeed/11/8",
# "https://www.dailysabah.com/rssFeed/11/9",
# "https://www.dailysabah.com/rssFeed/11/10",
# "https://www.dailysabah.com/rssFeed/11/11",
# "https://www.dailysabah.com/rssFeed/11/12",
# "https://www.dailysabah.com/rssFeed/12/13",
# "https://www.dailysabah.com/rssFeed/12/14",
# "https://www.dailysabah.com/rssFeed/12/15",
# "https://www.dailysabah.com/rssFeed/12/16",
# "https://www.dailysabah.com/rssFeed/12/17",
# "https://www.dailysabah.com/rssFeed/12/18",
# "https://www.dailysabah.com/rssFeed/12/19",
# "https://www.dailysabah.com/rssFeed/13/20",
# "https://www.dailysabah.com/rssFeed/13/21",
# "https://www.dailysabah.com/rssFeed/13/22",
# "https://www.dailysabah.com/rssFeed/13/23",
# "https://www.dailysabah.com/rssFeed/13/24",
# "https://www.dailysabah.com/rssFeed/13/25",
# "https://www.dailysabah.com/rssFeed/13/26",
# "https://www.dailysabah.com/rssFeed/13/27",
# "https://www.dailysabah.com/rssFeed/14/28",
# "https://www.dailysabah.com/rssFeed/14/29",
# "https://www.dailysabah.com/rssFeed/14/30",
# "https://www.dailysabah.com/rssFeed/14/31",
# "https://www.dailysabah.com/rssFeed/15/32",
# "https://www.dailysabah.com/rssFeed/15/33",
# "https://www.dailysabah.com/rssFeed/15/34",
# "https://www.dailysabah.com/rssFeed/15/35",
# "https://www.dailysabah.com/rssFeed/15/36",
# "https://www.dailysabah.com/rssFeed/15/37",
# "https://www.dailysabah.com/rssFeed/15/38",
# "https://www.dailysabah.com/rssFeed/15/39",
# "https://www.dailysabah.com/rssFeed/15/40",
# "https://www.dailysabah.com/rssFeed/16/43",
# "https://www.dailysabah.com/rssFeed/16/44",
# "https://www.dailysabah.com/rssFeed/16/45",
# "https://www.dailysabah.com/rssFeed/16/46",
# "https://www.dailysabah.com/rssFeed/16/47",
# "https://www.dailysabah.com/rssFeed/16/48",
# "https://www.dailysabah.com/rssFeed/17/49",
# "https://www.dailysabah.com/rssFeed/17/50",
# "https://www.dailysabah.com/rssFeed/17/51",
# "https://www.dailysabah.com/rssFeed/17/52",
# "https://betanews.com/feed/",
# "https://decrypt.co/feed",
# "https://www.bangkokpost.com/rss/data/most-recent.xml",
# "https://www.bangkokpost.com/rss/data/topstories.xml",
# "https://www.bangkokpost.com/rss/data/thailand.xml",
# "https://www.bangkokpost.com/rss/data/world.xml",
# "https://www.bangkokpost.com/rss/data/business.xml",
# "https://www.bangkokpost.com/rss/data/opinion.xml",
# "https://www.bangkokpost.com/rss/data/sports.xml",
# "https://www.bangkokpost.com/rss/data/life.xml",
# "https://www.bangkokpost.com/rss/data/learning.xml",
# "https://www.bangkokpost.com/rss/data/video.xml",
# "https://www.bangkokpost.com/rss/data/property.xml",
# "https://www.bangkokpost.com/rss/data/photos.xml",
# "http://www.gulf-times.com/rssFeed/9",
# "http://www.gulf-times.com/rssFeed/8",
# "http://www.gulf-times.com/rssFeed/10",
# "http://www.gulf-times.com/rssFeed/11",
# "http://www.gulf-times.com/rssFeed/12",
# "http://www.gulf-times.com/rssFeed/13",
# "http://www.gulf-times.com/rssFeed/6",
# "http://www.gulf-times.com/rssFeed/2",
# "http://www.gulf-times.com/rssFeed/3",
# "http://www.gulf-times.com/rssFeed/4",
# "http://www.gulf-times.com/rssFeed/7",
# "http://www.gulf-times.com/rssFeed/1",
# "http://www.gulf-times.com/rssFeed/5",
# "http://www.gulf-times.com/rssFeed/16",
# "http://www.gulf-times.com/rssFeed/15",
# "http://www.gulf-times.com/rssFeed/14",
# "http://www.gulf-times.com/rssFeed/18",
# "http://www.gulf-times.com/rssFeed/9/1",
# "http://www.gulf-times.com/rssFeed/9/2",
# "http://www.gulf-times.com/rssFeed/9/3",
# "http://www.gulf-times.com/rssFeed/9/4",
# "http://www.gulf-times.com/rssFeed/9/6",
# "http://www.gulf-times.com/rssFeed/9/7",
# "http://www.gulf-times.com/rssFeed/9/8",
# "http://www.gulf-times.com/rssFeed/9/9",
# "http://www.gulf-times.com/rssFeed/9/10",
# "http://www.gulf-times.com/rssFeed/9/11",
# "http://www.gulf-times.com/rssFeed/9/12",
# "http://www.gulf-times.com/rssFeed/9/13",
# "http://www.gulf-times.com/rssFeed/9/14",
# "http://www.gulf-times.com/rssFeed/9/15",
# "http://www.gulf-times.com/rssFeed/9/16",
# "http://www.gulf-times.com/rssFeed/9/17",
# "http://www.gulf-times.com/rssFeed/3/32",
# "http://www.gulf-times.com/rssFeed/5/18",
# "http://www.gulf-times.com/rssFeed/5/19",
# "http://www.gulf-times.com/rssFeed/5/20",
# "http://www.gulf-times.com/rssFeed/5/21",
# "http://www.gulf-times.com/rssFeed/5/22",
# "http://www.gulf-times.com/rssFeed/5/23",
# "http://www.gulf-times.com/rssFeed/5/24",
# "http://www.gulf-times.com/rssFeed/5/25",
# "http://www.gulf-times.com/rssFeed/5/26",
# "http://www.gulf-times.com/rssFeed/5/27",
# "http://www.gulf-times.com/rssFeed/5/28",
# "http://www.gulf-times.com/rssFeed/5/29",
# "https://crypto.news/feed/",
# "https://www.herald.co.zw/feed/",
# "https://www.ethnews.com/feed/",
# "https://www.businesspost.ie/feed/",
# "https://coinxposure.com/feed",
# "https://www.easa.europa.eu/newsroom-and-events/events/easa-events.feed.xml",
# "https://www.easa.europa.eu/newsroom-and-events/news/feed.xml",
# "https://www.easa.europa.eu/newsroom-and-events/press-releases/feed.xml",
# "https://www.easa.europa.eu/the-agency/procurement/calls-for-tender/feed.xml",
# "https://www.easa.europa.eu/document-library/application-forms/feed.xml",
# "https://www.easa.europa.eu/document-library/agency-decisions/feed.xml",
# "https://www.easa.europa.eu/document-library/acceptable-means-of-compliance-and-guidance-materials/feed.xml",
# "https://www.easa.europa.eu/document-library/certification-specifications/feed.xml",
# "https://www.easa.europa.eu/document-library/regulations/feed.xml",
# "https://www.easa.europa.eu/en/document-library/easy-access-rules/feed.xml",
# "https://www.easa.europa.eu/document-library/rulemaking-programmes/feed.xml",
# "https://www.easa.europa.eu/document-library/terms-of-reference-and-group-compositions/feed.xml",
# "https://www.easa.europa.eu/document-library/notices-of-proposed-amendment/feed.xml",
# "https://www.easa.europa.eu/document-library/comment-response-documents/feed.xml",
# "https://www.easa.europa.eu/document-library/opinions/feed.xml",
# "https://www.easa.europa.eu/document-library/product-certification-consultations/feed.xml",
# "https://www.easa.europa.eu/document-library/type-certificates/feed.xml",
# "https://www.easa.europa.eu/document-library/type-certificates/tcdsn/feed.xml",
# "https://www.easa.europa.eu/document-library/specific-airworthiness-specifications/feed.xml",
# "https://www.easa.europa.eu/document-library/master-minimum-equipment-lists/feed.xml",
# "https://www.easa.europa.eu/document-library/operational-suitability-data/feed.xml",
# "http://www.easa.europa.eu/document-library/certification-procedures/feed.xml",
# "https://www.easa.europa.eu/document-library/bilateral-agreements/feed.xml",
# "https://www.easa.europa.eu/document-library/working-arrangements/feed.xml",
# "https://www.easa.europa.eu/document-library/research-reports/feed.xml",
# "https://www.easa.europa.eu/document-library/general-publications/feed.xml",
# "https://www.easa.europa.eu/en/document-library/easy-access-rules/feed.xml",
# "https://www.easa.europa.eu/easa-and-you/aircraft-products/suspected-unapproved-parts/feed.xml",
# "https://www.ledgerinsights.com/feed/",
# "https://financefeeds.com/feed/",
# "https://www.scmp.com/rss/91/feed",
# "https://www.scmp.com/rss/2/feed",
# "https://www.scmp.com/rss/4/feed",
# "https://www.scmp.com/rss/3/feed",
# "https://www.scmp.com/rss/5/feed",
# "https://www.scmp.com/rss/318198/feed",
# "https://www.scmp.com/rss/318199/feed",
# "https://www.scmp.com/rss/318200/feed",
# "https://www.scmp.com/rss/318421/feed",
# "https://www.scmp.com/rss/318202/feed",
# "https://www.scmp.com/rss/318206/feed",
# "https://www.scmp.com/rss/318210/feed",
# "https://www.scmp.com/rss/318208/feed",
# "https://www.scmp.com/rss/318217/feed",
# "https://www.scmp.com/rss/318207/feed",
# "https://www.scmp.com/rss/322262/feed",
# "https://www.scmp.com/rss/322263/feed",
# "https://www.scmp.com/rss/322264/feed",
# "https://www.scmp.com/rss/322265/feed",
# "https://www.scmp.com/rss/322266/feed",
# "https://www.scmp.com/rss/322514/feed",
# "https://www.scmp.com/rss/322243/feed",
# "https://www.scmp.com/rss/318213/feed",
# "https://www.scmp.com/rss/318214/feed",
# "https://www.scmp.com/rss/318215/feed",
# "https://www.scmp.com/rss/318216/feed",
# "https://www.scmp.com/rss/92/feed",
# "https://www.scmp.com/rss/10/feed",
# "https://www.scmp.com/rss/96/feed",
# "https://www.scmp.com/rss/7/feed",
# "https://www.scmp.com/rss/12/feed",
# "https://www.scmp.com/rss/318421/feed",
# "https://www.scmp.com/rss/318200/feed",
# "https://www.scmp.com/rss/6/feed",
# "https://www.scmp.com/rss/17/feed",
# "https://www.scmp.com/rss/76670/feed",
# "https://www.scmp.com/rss/19/feed",
# "https://www.scmp.com/rss/21/feed",
# "https://www.scmp.com/rss/22/feed",
# "https://www.scmp.com/rss/96/feed",
# "https://www.scmp.com/rss/43/feed",
# "https://www.scmp.com/rss/44/feed",
# "https://www.scmp.com/rss/36/feed",
# "https://www.scmp.com/rss/320663/feed",
# "https://www.scmp.com/rss/318218/feed",
# "https://www.scmp.com/rss/318219/feed",
# "https://www.scmp.com/rss/318220/feed",
# "https://www.scmp.com/rss/318221/feed",
# "https://www.scmp.com/rss/318222/feed",
# "https://www.scmp.com/rss/318223/feed",
# "https://www.scmp.com/rss/318224/feed",
# "https://www.scmp.com/rss/318225/feed",
# "https://www.scmp.com/rss/94/feed",
# "https://www.scmp.com/rss/28/feed",
# "https://www.scmp.com/rss/37/feed",
# "https://www.scmp.com/rss/35/feed",
# "https://www.scmp.com/rss/30/feed",
# "https://www.scmp.com/rss/24/feed",
# "https://www.scmp.com/rss/318256/feed",
# "https://www.scmp.com/rss/322296/feed",
# "https://www.scmp.com/rss/25/feed",
# "https://www.scmp.com/rss/318255/feed",
# "https://www.scmp.com/rss/318254/feed",
# "https://www.scmp.com/rss/23/feed",
# "https://www.scmp.com/rss/95/feed",
# "https://www.scmp.com/rss/38/feed",
# "https://www.scmp.com/rss/41/feed",
# "https://www.scmp.com/rss/116/feed",
# "https://www.scmp.com/rss/39/feed",
# "https://www.scmp.com/rss/310895/feed",
# "https://www.scmp.com/rss/40/feed",
# "https://www.scmp.com/rss/117/feed",
# "https://www.scmp.com/rss/47492/feed",
# "https://www.scmp.com/rss/318217/feed",
# "https://www.scmp.com/rss/71/feed",
# "https://www.scmp.com/rss/322658/feed",
# "https://www.scmp.com/rss/322659/feed",
# "https://www.scmp.com/rss/321716/feed",
# "https://www.scmp.com/rss/321721/feed",
# "https://www.scmp.com/rss/321719/feed",
# "https://www.scmp.com/rss/321720/feed",
# "https://www.scmp.com/rss/321713/feed",
# "https://www.scmp.com/rss/72/feed",
# "https://www.scmp.com/rss/322896/feed",
# "https://www.scmp.com/rss/322897/feed",
# "https://www.scmp.com/rss/322898/feed",
# "https://www.scmp.com/rss/322899/feed",
# "https://www.scmp.com/rss/322900/feed",
# "https://www.scmp.com/rss/322901/feed",
# "https://www.scmp.com/rss/323045/feed",
# "https://www.scmp.com/rss/323046/feed",
# "https://www.scmp.com/rss/323047/feed",
# "https://www.scmp.com/rss/323048/feed",
# "https://www.scmp.com/rss/323049/feed",
# "https://www.scmp.com/rss/323050/feed",
# "https://www.scmp.com/rss/323051/feed",
# "https://www.scmp.com/rss/323052/feed",
# "https://www.scmp.com/rss/506035/feed",
# "https://www.scmp.com/rss/506036/feed",
# "https://www.scmp.com/rss/506037/feed",
# "https://www.scmp.com/rss/506038/feed",
# "https://www.scmp.com/rss/506044/feed",
# "https://www.scmp.com/rss/506039/feed",
# "https://www.scmp.com/rss/506042/feed",
# "https://www.scmp.com/rss/505323/feed",
# "https://www.scmp.com/rss/505356/feed",
# "https://www.scmp.com/rss/505326/feed",
# "https://www.scmp.com/rss/505325/feed",
# "https://www.scmp.com/rss/505354/feed",
# "https://www.scmp.com/rss/505355/feed",
# "https://www.scmp.com/rss/505328/feed",
# "https://www.scmp.com/rss/505327/feed",
# "https://www.scmp.com/rss/505324/feed",
# "https://www.scmp.com/rss/502060/feed",
# "https",
# "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
# "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
# "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6936",
# "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416",
# "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10296",
# "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6311",
# "https://www.fso.gov.hk/rss/fsblog_rss_t.xml",
# "https://www.censtatd.gov.hk/data/tc/press_release/rss.xml",
# "https://www.news.gov.hk/tc/common/html/ticker.rss.xml",
# "https://www.news.gov.hk/tc/feature/index.rss.xml",
# "https://www.news.gov.hk/tc/common/html/topstories.rss.xml",
# "https://www.news.gov.hk/tc/categories/admin/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/categories/school_work/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/categories/finance/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/city_life/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/categories/environment/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/categories/health/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/categories/infrastructure/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/categories/law_order/html/articlelist.rss.xml",
# "https://www.news.gov.hk/tc/record/html/articlelist.rss.xml",
# "https://www.info.gov.hk/gia/rss/general_zh.xml",
# "https://rss.weather.gov.hk/rss/WeatherWarningSummaryv2_uc.xml",
# "https://rss.weather.gov.hk/rss/LocalWeatherForecast_uc.xml",
# "https://rss.weather.gov.hk/rss/CurrentWeather_uc.xml",
# "https://rss.weather.gov.hk/rss/SeveralDaysWeatherForecast_uc.xml",
# "https://www.gov.hk/tc/theme/bf/feeds/bf-news.data.xml",
# "https://www.gov.hk/tc/theme/bf/feeds/business-consultation.data.xml",
# "https://www.mardep.gov.hk/filemanager/tc/share/news/rss1c.xml",
# "https://www.lcsd.gov.hk/tc/emagazine/emag_rss.xml",
# "https://www.edb.gov.hk/en/whats_new_rss.xml",
# "https://www.epd.gov.hk/epd/tc_chi/rss_feeds/highlights.xml",
# "https://www.epd.gov.hk/epd/tc_chi/rss_feeds/events_acts.xml",
# "http://www.aqhi.gov.hk/epd/ddata/html/out/aqhirss_ChT.xml",
# "https://www.chp.gov.hk/rss/pressreleases_zh_tw_RSS.xml",
# "https://www.chp.gov.hk/rss/cdwatch_zh_tw_RSS.xml",
# "https://www.chp.gov.hk/rss/ncdaware_zh_tw_RSS.xml",
# "https://www.chp.gov.hk/rss/newsletter_zh_tw_RSS.xml",
# "https://www.chp.gov.hk/rss/publication_zh_tw_RSS.xml",
# "https://www.chp.gov.hk/rss/tne_event_zh_tw_RSS.xml",
# "https://www.ofca.gov.hk/filemanager/ofca/tc/rss/index.xml",
# "https://www.hongkongpost.hk/tc/about_us/whats_new/press_release/press_release.xml",
# "https://www.hongkongpost.hk/tc/about_us/whats_new/notices/notices.xml",
# "https://blockworks.co/feed",
# "https://www.cbc.ca/webfeed/rss/rss-topstories",
# "https://www.cbc.ca/webfeed/rss/rss-world",
# "https://www.cbc.ca/webfeed/rss/rss-canada",
# "https://www.cbc.ca/webfeed/rss/rss-politics",
# "https://www.cbc.ca/webfeed/rss/rss-business",
# "https://www.cbc.ca/webfeed/rss/rss-health",
# "https://www.cbc.ca/webfeed/rss/rss-arts",
# "https://www.cbc.ca/webfeed/rss/rss-technology",
# "https://www.cbc.ca/webfeed/rss/rss-Indigenous",
# "https://www.cbc.ca/webfeed/rss/rss-sports",
# "https://www.cbc.ca/webfeed/rss/rss-sports-mlb",
# "https://www.cbc.ca/webfeed/rss/rss-sports-nba",
# "https://www.cbc.ca/webfeed/rss/rss-sports-curling",
# "https://www.cbc.ca/webfeed/rss/rss-sports-cfl",
# "https://www.cbc.ca/webfeed/rss/rss-sports-nfl",
# "https://www.cbc.ca/webfeed/rss/rss-sports-nhl",
# "https://www.cbc.ca/webfeed/rss/rss-sports-soccer",
# "https://www.cbc.ca/webfeed/rss/rss-sports-figureskating",
# "https://www.cbc.ca/webfeed/rss/rss-sports-golf",
# "https://www.cbc.ca/webfeed/rss/rss-sports-olympics",
# "https://www.cbc.ca/webfeed/rss/rss-sports-skiing",
# "https://www.cbc.ca/webfeed/rss/rss-sports-tennis",
# "https://www.cbc.ca/webfeed/rss/rss-canada-britishcolumbia",
# "https://www.cbc.ca/webfeed/rss/rss-canada-kamloops",
# "https://www.cbc.ca/webfeed/rss/rss-canada-calgary",
# "https://www.cbc.ca/webfeed/rss/rss-canada-edmonton",
# "https://www.cbc.ca/webfeed/rss/rss-canada-saskatchewan",
# "https://www.cbc.ca/webfeed/rss/rss-canada-saskatoon",
# "https://www.cbc.ca/webfeed/rss/rss-canada-manitoba",
# "https://www.cbc.ca/webfeed/rss/rss-canada-thunderbay",
# "https://www.cbc.ca/webfeed/rss/rss-canada-sudbury",
# "https://www.cbc.ca/webfeed/rss/rss-canada-windsor",
# "https://www.cbc.ca/webfeed/rss/rss-canada-london",
# "https://www.cbc.ca/webfeed/rss/rss-canada-kitchenerwaterloo",
# "https://www.cbc.ca/webfeed/rss/rss-canada-toronto",
# "https://www.cbc.ca/webfeed/rss/rss-canada-hamiltonnews",
# "https://www.cbc.ca/webfeed/rss/rss-canada-montreal",
# "https://www.cbc.ca/webfeed/rss/rss-canada-newbrunswick",
# "https://www.cbc.ca/webfeed/rss/rss-canada-pei",
# "https://www.cbc.ca/webfeed/rss/rss-canada-novascotia",
# "https://www.cbc.ca/webfeed/rss/rss-canada-newfoundland",
# "https://www.cbc.ca/webfeed/rss/rss-canada-north",
# "https://www.cbc.ca/webfeed/rss/rss-canada-ottawa",
# "https://sdg.iisd.org/feed/",
# "https://www.forexlive.com/feed",
# "https://www.forexlive.com/feed/news",
# "https://www.forexlive.com/feed/technicalanalysis",
# "https://www.forexlive.com/feed/forexorders",
# "https://www.forexlive.com/feed/centralbank",
# "https://www.forexlive.com/feed/education",
# "https://www.forexlive.com/feed/cryptocurrency",
# "https://feedly.com/#subscription/feed/",
# "https://www.thehindu.com/feeder/default.rss",
# "https://www.thehindu.com/theme/images/th-online/rss-img1.png",
# "https://www.thehindu.com/theme/images/th-online/rss-img2.png",
# "https://www.thehindu.com/theme/images/th-online/rss-img3.png",
# "https://www.thehindu.com/news/feeder/default.rss",
# "https://www.thehindu.com/news/national/feeder/default.rss",
# "https://www.thehindu.com/news/international/feeder/default.rss",
# "https://www.thehindu.com/news/states/feeder/default.rss",
# "https://www.thehindu.com/news/cities/feeder/default.rss",
# "https://www.thehindu.com/opinion/feeder/default.rss",
# "https://www.thehindu.com/opinion/cartoon/feeder/default.rss",
# "https://www.thehindu.com/opinion/columns/feeder/default.rss",
# "https://www.thehindu.com/opinion/op-ed/feeder/default.rss",
# "https://www.thehindu.com/opinion/editorial/feeder/default.rss",
# "https://www.thehindu.com/opinion/interview/feeder/default.rss",
# "https://www.thehindu.com/opinion/lead/feeder/default.rss",
# "https://www.thehindu.com/opinion/letters/feeder/default.rss",
# "https://www.thehindu.com/opinion/open-page/feeder/default.rss",
# "https://www.thehindu.com/opinion/Readers-Editor/feeder/default.rss",
# "https://www.thehindu.com/opinion/Readers-Editor/corrections-and-clarifications/feeder/default.rss",
# "https://www.thehindu.com/business/feeder/default.rss",
# "https://www.thehindu.com/business/agri-business/feeder/default.rss",
# "https://www.thehindu.com/business/Industry/feeder/default.rss",
# "https://www.thehindu.com/business/Economy/feeder/default.rss",
# "https://www.thehindu.com/business/markets/feeder/default.rss",
# "https://www.thehindu.com/business/budget/feeder/default.rss",
# "https://www.thehindu.com/business/feeder/default.rss",
# "https://www.thehindu.com/business/agri-business/feeder/default.rss",
# "https://www.thehindu.com/business/Industry/feeder/default.rss",
# "https://www.thehindu.com/business/Economy/feeder/default.rss",
# "https://www.thehindu.com/business/markets/feeder/default.rss",
# "https://www.thehindu.com/business/budget/feeder/default.rss",
# "https://www.thehindu.com/sport/feeder/default.rss",
# "https://www.thehindu.com/sport/cricket/feeder/default.rss",
# "https://www.thehindu.com/sport/football/feeder/default.rss",
# "https://www.thehindu.com/sport/hockey/feeder/default.rss",
# "https://www.thehindu.com/sport/tennis/feeder/default.rss",
# "https://www.thehindu.com/sport/athletics/feeder/default.rss",
# "https://www.thehindu.com/sport/motorsport/feeder/default.rss",
# "https://www.thehindu.com/sport/races/feeder/default.rss",
# "https://www.thehindu.com/sport/other-sports/feeder/default.rss",
# "https://www.thehindu.com/entertainment/feeder/default.rss",
# "https://www.thehindu.com/entertainment/art/feeder/default.rss",
# "https://www.thehindu.com/entertainment/dance/feeder/default.rss",
# "https://www.thehindu.com/entertainment/movies/feeder/default.rss",
# "https://www.thehindu.com/entertainment/music/feeder/default.rss",
# "https://www.thehindu.com/entertainment/reviews/feeder/default.rss",
# "https://www.thehindu.com/entertainment/theatre/feeder/default.rss",
# "https://crossword.thehindu.com/?utm_source=thehindu&amp;utm_medium=mainmenufeeder/default.rss",
# "https://www.thehindu.com/sci-tech/science/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/fashion/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/fitness/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/food/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/motoring/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/travel/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/homes-and-gardens/feeder/default.rss",
# "https://www.thehindu.com/life-and-style/luxury/feeder/default.rss",
# "https://rss.timesofmalta.com/",
# "https://www.biometricupdate.com/feed",
# "https://www.pymnts.com/feed/",
# "https://www.nation.com.pk/rss/advertising",
# "https://www.nation.com.pk/rss/blogs",
# "https://www.nation.com.pk/rss/breaking-news",
# "https://www.nation.com.pk/rss/business",
# "https://www.nation.com.pk/rss/editors-picks",
# "https://www.nation.com.pk/rss/education",
# "https://www.nation.com.pk/rss/events",
# "https://www.nation.com.pk/rss/headlines",
# "https://www.nation.com.pk/rss/international",
# "https://www.nation.com.pk/rss/lifestyle-entertainment",
# "https://www.nation.com.pk/rss/multimedia",
# "https://www.nation.com.pk/rss/national",
# "https://www.nation.com.pk/rss/newspaper",
# "https://www.nation.com.pk/rss/obituary",
# "https://www.nation.com.pk/rss/opinions",
# "https://www.nation.com.pk/rss/politics",
# "https://www.nation.com.pk/rss/regional",
# "https://www.nation.com.pk/rss/sports",
# "https://www.nation.com.pk/rss/technology",
# "https://arstechnica.com/feed/",
# "https://forklog.com/feed",
# "https://www.livemint.com/rss/companiesRSS",
# "https://www.livemint.com/rss/opinionRSS",
# "https://www.livemint.com/rss/moneyRSS",
# "https://www.livemint.com/rss/politicsRSS",
# "https://www.livemint.com/rss/scienceRSS",
# "https://www.livemint.com/rss/industryRSS",
# "https://www.livemint.com/rss/educationRSS",
# "https://www.livemint.com/rss/sportsRSS",
# "https://www.livemint.com/rss/technologyRSS",
# "https://www.livemint.com/rss/newsRSS",
# "https://www.livemint.com/rss/marketsRSS",
# "https://www.livemint.com/rss/AIRSS",
# "https://www.livemint.com/rss/insuranceRSS",
# "https://www.livemint.com/rss/budgetRSS",
# "https://www.livemint.com/rss/electionsRSS",
# "https://www.livemint.com/rss/videos",
# "https://www.bis.org/doclist/rss_all_categories.rss	",
# "https://www.bis.org/doclist/all_pressrels.rss	",
# "https://www.bis.org/doclist/vacancies.rss	",
# "https://www.bis.org/doclist/bis_fsi_publs.rss	",
# "https://www.bis.org/doclist/cbspeeches.rss	",
# "https://www.bis.org/doclist/mgmtspeeches.rss	",
# "https://www.bis.org/doclist/all_statistics.rss	",
# "https://www.bis.org/doclist/rss_translations_de.rss	",
# "https://www.bis.org/doclist/rss_translations_es.rss	",
# "https://www.bis.org/doclist/rss_translations_fr.rss	",
# "https://www.bis.org/doclist/rss_translations_it.rss	",
# "https://www.bis.org/doclist/reshub_papers.rss",
# "https://www.techrepublic.com/feed/",
# "https://www.mckinsey.com/insights/rss",
# "https://techinformed.com/feed/rss2/",
# "https://www.digitaljournal.com/feed",
# "https://tech.hindustantimes.com/rss/tech",
# "https://tech.hindustantimes.com/rss/tech/news",
# "https://tech.hindustantimes.com/rss/mobile",
# "https://tech.hindustantimes.com/rss/mobile/news",
# "https://tech.hindustantimes.com/rss/mobile/reviews",
# "https://tech.hindustantimes.com/rss/laptops-pc",
# "https://tech.hindustantimes.com/rss/laptops-pc/news",
# "https://tech.hindustantimes.com/rss/laptops-pc/reviews",
# "https://tech.hindustantimes.com/rss/wearables",
# "https://tech.hindustantimes.com/rss/wearables/news",
# "https://tech.hindustantimes.com/rss/wearables/reviews",
# "https://tech.hindustantimes.com/rss/gaming",
# "https://tech.hindustantimes.com/rss/photos",
# "https://tech.hindustantimes.com/rss/videos",
# "https://tech.hindustantimes.com/rss/how-to",
# "https://tech.hindustantimes.com/rss/tv",
# "https://tech.hindustantimes.com/rss/tv/news",
# "https://tech.hindustantimes.com/rss/tv/reviews",
# "https://tech.hindustantimes.com/rss/home-appliances",
# "https://tech.hindustantimes.com/rss/web-stories",
# "https://coingeek.com/feed/",
# "https://www.uktech.news/feed",
# "https://www.computerweekly.com/rss/About-RSS",
# "https://www.computerweekly.com/rss/RSS-Feed.xml",
# "https://www.computerweekly.com/rss/ContentSyndication.xml",
# "https://www.computerweekly.com/rss/All-Computer-Weekly-content.xml",
# "https://www.computerweekly.com/rss/Latest-IT-news.xml",
# "https://www.computerweekly.com/rss/IT-management.xml",
# "https://www.computerweekly.com/rss/IT-careers-and-IT-skills.xml",
# "https://www.computerweekly.com/rss/Enterprise-software.xml",
# "https://www.computerweekly.com/rss/IT-services-and-outsourcing.xml",
# "https://www.computerweekly.com/rss/IT-security.xml",
# "https://www.computerweekly.com/rss/Networking-and-communication.xml",
# "https://www.computerweekly.com/rss/Mobile-technology.xml",
# "https://www.computerweekly.com/rss/Internet-technology.xml",
# "https://www.computerweekly.com/rss/IT-hardware.xml",
# "https://www.computerweekly.com/rss/Public-sector-IT-news.xml",
# "https://www.computerweekly.com/rss/Financial-services-IT-news.xml",
# "https://www.computerweekly.com/rss/SME-IT-news.xml",
# "https://www.computerweekly.com/rss/Video.xml",
# "https://www.computerweekly.com/rss/Photo-stories.xml",
# "https://www.computerweekly.com/rss/Datacentre-and-cloud-computing.xml",
# "https://www.computerweekly.com/rss/Storage.xml",
# "https://www.computerweekly.com/rss/Information-management.xml",
# "https://www.computerweekly.com/rss/Nordics.xml",
# "https://www.computerweekly.com/rss/ANZ.xml",
# "https://www.computerweekly.com/rss/ASEAN.xml",
# "https://www.computerweekly.com/rss/Asia-Pacific.xml",
# "https://www.computerweekly.com/editorspicks",
# "https://www.computerweekly.com/rss/Computer-Weekly-Downtime-Upload.xml",
# "https://tribuneonlineng.com/feed/"]
links = ["https://www.ecb.europa.eu/rss/press.html",
         "https://www.ecb.europa.eu/rss/blog.html",
         "https://www.ecb.europa.eu/rss/statpress.html",
         "https://www.ecb.europa.eu/rss/pub.html",
         "https://www.ecb.europa.eu/rss/procurements.html",
         "https://www.techradar.com/rss",
         "https://www.the-star.co.ke/rss",
         "https://kuwaittimes.com/rssFeed/0",
         "https://kuwaittimes.com/rssFeed/10",
         "https://kuwaittimes.com/rssFeed/1",
         "https://kuwaittimes.com/rssFeed/5",
         "https://kuwaittimes.com/rssFeed/9",
         "https://kuwaittimes.com/rssFeed/11",
         "https://kuwaittimes.com/rssFeed/12",
         "https://kuwaittimes.com/rssFeed/13",
         "https://kuwaittimes.com/rssFeed/14",
         "https://kuwaittimes.com/rssFeed/15",
         "https://kuwaittimes.com/rssFeed/18",
         "https://kuwaittimes.com/rssFeed/17",
         "https://kuwaittimes.com/rssFeed/20",
         "https://www.laprensalatina.com/feed/",
         "https://creativecommons.org/feed/",
         "https://www.silicon.co.uk/feed",
         "https://www.euractiv.com/feed/",
         "https://www.dailysabah.com/rssFeed/10/1",
         "https://www.dailysabah.com/rssFeed/10/2",
         "https://www.dailysabah.com/rssFeed/10/3",
         "https://www.dailysabah.com/rssFeed/10/4",
         "https://www.dailysabah.com/rssFeed/10/6",
         "https://www.dailysabah.com/rssFeed/11/7",
         "https://www.dailysabah.com/rssFeed/11/8",
         "https://www.dailysabah.com/rssFeed/11/10",
         "https://www.dailysabah.com/rssFeed/11/12",
         "https://www.dailysabah.com/rssFeed/12/13",
         "https://www.dailysabah.com/rssFeed/12/14",
         "https://www.dailysabah.com/rssFeed/12/15",
         "https://www.dailysabah.com/rssFeed/12/16",
         "https://www.dailysabah.com/rssFeed/12/17",
         "https://www.dailysabah.com/rssFeed/12/18",
         "https://www.dailysabah.com/rssFeed/12/19",
         "https://www.dailysabah.com/rssFeed/13/20",
         "https://www.dailysabah.com/rssFeed/13/21",
         "https://www.dailysabah.com/rssFeed/13/22",
         "https://www.dailysabah.com/rssFeed/13/23",
         "https://www.dailysabah.com/rssFeed/13/24",
         "https://www.dailysabah.com/rssFeed/13/25",
         "https://www.dailysabah.com/rssFeed/13/26",
         "https://www.dailysabah.com/rssFeed/13/27",
         "https://www.dailysabah.com/rssFeed/14/28",
         "https://www.dailysabah.com/rssFeed/15/33",
         "https://www.dailysabah.com/rssFeed/15/34",
         "https://www.dailysabah.com/rssFeed/15/36",
         "https://www.dailysabah.com/rssFeed/15/38",
         "https://www.dailysabah.com/rssFeed/15/39",
         "https://www.dailysabah.com/rssFeed/17/50",
         "https://www.dailysabah.com/rssFeed/17/52",
         "https://betanews.com/feed/",
         "https://www.bangkokpost.com/rss/data/most-recent.xml",
         "https://www.bangkokpost.com/rss/data/thailand.xml",
         "https://www.bangkokpost.com/rss/data/business.xml",
         # "https://www.bangkokpost.com/rss/data/video.xml",
         # "https://www.bangkokpost.com/rss/data/photos.xml",
         "http://www.gulf-times.com/rssFeed/9",
         "http://www.gulf-times.com/rssFeed/8",
         "http://www.gulf-times.com/rssFeed/10",
         "http://www.gulf-times.com/rssFeed/11",
         "http://www.gulf-times.com/rssFeed/13",
         "http://www.gulf-times.com/rssFeed/6",
         "http://www.gulf-times.com/rssFeed/2",
         "http://www.gulf-times.com/rssFeed/4",
         "http://www.gulf-times.com/rssFeed/5",
         "http://www.gulf-times.com/rssFeed/15",
         "http://www.gulf-times.com/rssFeed/14",
         "http://www.gulf-times.com/rssFeed/18",
         "http://www.gulf-times.com/rssFeed/9/1",
         "http://www.gulf-times.com/rssFeed/9/2",
         "http://www.gulf-times.com/rssFeed/9/3",
         "http://www.gulf-times.com/rssFeed/9/4",
         "http://www.gulf-times.com/rssFeed/9/6",
         "http://www.gulf-times.com/rssFeed/9/7",
         "http://www.gulf-times.com/rssFeed/9/8",
         "http://www.gulf-times.com/rssFeed/9/9",
         "http://www.gulf-times.com/rssFeed/9/10",
         "http://www.gulf-times.com/rssFeed/9/11",
         "http://www.gulf-times.com/rssFeed/9/12",
         "http://www.gulf-times.com/rssFeed/9/13",
         "http://www.gulf-times.com/rssFeed/9/14",
         "http://www.gulf-times.com/rssFeed/9/15",
         "http://www.gulf-times.com/rssFeed/9/16",
         "http://www.gulf-times.com/rssFeed/9/17",
         "http://www.gulf-times.com/rssFeed/3/32",
         "http://www.gulf-times.com/rssFeed/5/18",
         "http://www.gulf-times.com/rssFeed/5/19",
         "http://www.gulf-times.com/rssFeed/5/20",
         "http://www.gulf-times.com/rssFeed/5/21",
         "http://www.gulf-times.com/rssFeed/5/22",
         "http://www.gulf-times.com/rssFeed/5/23",
         "http://www.gulf-times.com/rssFeed/5/24",
         "http://www.gulf-times.com/rssFeed/5/25",
         "http://www.gulf-times.com/rssFeed/5/26",
         "http://www.gulf-times.com/rssFeed/5/27",
         "http://www.gulf-times.com/rssFeed/5/28",
         "http://www.gulf-times.com/rssFeed/5/29",
         "https://crypto.news/feed/",
         "https://www.ethnews.com/feed/",
         "https://coinxposure.com/feed",
         "https://coinpedia.org/feed/",
         "https://coingeek.com/feed/",
         "https://www.easa.europa.eu/newsroom-and-events/events/easa-events.feed.xml",
         "https://www.easa.europa.eu/newsroom-and-events/news/feed.xml",
         "https://www.easa.europa.eu/newsroom-and-events/press-releases/feed.xml",
         "https://www.easa.europa.eu/en/document-library/easy-access-rules/feed.xml",
         "https://www.easa.europa.eu/document-library/rulemaking-programmes/feed.xml",
         "http://www.easa.europa.eu/document-library/certification-procedures/feed.xml",
         "https://www.easa.europa.eu/document-library/working-arrangements/feed.xml",
         "https://www.easa.europa.eu/document-library/research-reports/feed.xml",
         "https://www.easa.europa.eu/document-library/general-publications/feed.xml",
         "https://www.easa.europa.eu/en/document-library/easy-access-rules/feed.xml",
         "https://www.ledgerinsights.com/feed/",
         "https://financefeeds.com/feed/",
         "https://www.scmp.com/rss/91/feed",
         "https://www.scmp.com/rss/2/feed",
         "https://www.scmp.com/rss/4/feed",
         "https://www.scmp.com/rss/3/feed",
         "https://www.scmp.com/rss/5/feed",
         "https://www.scmp.com/rss/318198/feed",
         "https://www.scmp.com/rss/318199/feed",
         "https://www.scmp.com/rss/318200/feed",
         "https://www.scmp.com/rss/318421/feed",
         "https://www.scmp.com/rss/318206/feed",
         "https://www.scmp.com/rss/318210/feed",
         "https://www.scmp.com/rss/318208/feed",
         "https://www.scmp.com/rss/318207/feed",
         "https://www.scmp.com/rss/322262/feed",
         "https://www.scmp.com/rss/322263/feed",
         "https://www.scmp.com/rss/322264/feed",
         "https://www.scmp.com/rss/322265/feed",
         "https://www.scmp.com/rss/322266/feed",
         "https://www.scmp.com/rss/322243/feed",
         "https://www.scmp.com/rss/318213/feed",
         "https://www.scmp.com/rss/318214/feed",
         "https://www.scmp.com/rss/318215/feed",
         "https://www.scmp.com/rss/318216/feed",
         "https://www.scmp.com/rss/92/feed",
         "https://www.scmp.com/rss/10/feed",
         "https://www.scmp.com/rss/96/feed",
         "https://www.scmp.com/rss/7/feed",
         "https://www.scmp.com/rss/12/feed",
         "https://www.scmp.com/rss/318421/feed",
         "https://www.scmp.com/rss/318200/feed",
         "https://www.scmp.com/rss/6/feed",
         "https://www.scmp.com/rss/17/feed",
         "https://www.scmp.com/rss/22/feed",
         "https://www.scmp.com/rss/96/feed",
         "https://www.scmp.com/rss/43/feed",
         "https://www.scmp.com/rss/44/feed",
         "https://www.scmp.com/rss/36/feed",
         "https://www.scmp.com/rss/320663/feed",
         "https://www.scmp.com/rss/318218/feed",
         "https://www.scmp.com/rss/318222/feed",
         "https://www.scmp.com/rss/318223/feed",
         "https://www.scmp.com/rss/318224/feed",
         "https://www.scmp.com/rss/94/feed",
         "https://www.scmp.com/rss/37/feed",
         "https://www.scmp.com/rss/35/feed",
         "https://www.scmp.com/rss/47492/feed",
         "https://www.scmp.com/rss/322900/feed",
         "https://www.scmp.com/rss/323046/feed",
         "https://www.scmp.com/rss/323047/feed",
         "https://www.scmp.com/rss/323048/feed",
         "https://www.scmp.com/rss/323050/feed",
         "https://www.scmp.com/rss/506036/feed",
         "https://www.scmp.com/rss/506042/feed",
         "https://www.scmp.com/rss/505323/feed",
         "https://www.scmp.com/rss/505356/feed",
         "https://www.scmp.com/rss/505326/feed",
         "https://www.scmp.com/rss/505354/feed",
         "https://www.scmp.com/rss/505355/feed",
         "https://www.scmp.com/rss/505328/feed",
         "https://www.scmp.com/rss/505327/feed",
         "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
         "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
         "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6936",
         "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416",
         "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10296",
         "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6311",
         "https://blockworks.co/feed",
         "https://www.cbc.ca/webfeed/rss/rss-topstories",
         "https://www.cbc.ca/webfeed/rss/rss-world",
         "https://www.cbc.ca/webfeed/rss/rss-canada",
         "https://www.cbc.ca/webfeed/rss/rss-politics",
         "https://www.cbc.ca/webfeed/rss/rss-business",
         "https://www.cbc.ca/webfeed/rss/rss-Indigenous",
         # "https://www.cbc.ca/webfeed/rss/rss-sports",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-mlb",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-nba",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-curling",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-cfl",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-nfl",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-nhl",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-soccer",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-figureskating",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-golf",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-olympics",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-skiing",
         # "https://www.cbc.ca/webfeed/rss/rss-sports-tennis",
         "https://www.cbc.ca/webfeed/rss/rss-canada-britishcolumbia",
         "https://www.cbc.ca/webfeed/rss/rss-canada-kamloops",
         "https://www.cbc.ca/webfeed/rss/rss-canada-calgary",
         "https://www.cbc.ca/webfeed/rss/rss-canada-edmonton",
         "https://www.cbc.ca/webfeed/rss/rss-canada-saskatchewan",
         "https://www.cbc.ca/webfeed/rss/rss-canada-saskatoon",
         "https://www.cbc.ca/webfeed/rss/rss-canada-manitoba",
         "https://www.cbc.ca/webfeed/rss/rss-canada-thunderbay",
         "https://www.cbc.ca/webfeed/rss/rss-canada-sudbury",
         "https://www.cbc.ca/webfeed/rss/rss-canada-windsor",
         "https://www.cbc.ca/webfeed/rss/rss-canada-london",
         "https://www.cbc.ca/webfeed/rss/rss-canada-kitchenerwaterloo",
         "https://www.cbc.ca/webfeed/rss/rss-canada-toronto",
         "https://www.cbc.ca/webfeed/rss/rss-canada-hamiltonnews",
         "https://www.cbc.ca/webfeed/rss/rss-canada-montreal",
         "https://www.cbc.ca/webfeed/rss/rss-canada-newbrunswick",
         "https://www.cbc.ca/webfeed/rss/rss-canada-pei",
         "https://www.cbc.ca/webfeed/rss/rss-canada-novascotia",
         "https://www.cbc.ca/webfeed/rss/rss-canada-newfoundland",
         "https://www.cbc.ca/webfeed/rss/rss-canada-north",
         "https://www.cbc.ca/webfeed/rss/rss-canada-ottawa",
         "https://sdg.iisd.org/feed/",
         "https://www.forexlive.com/feed",
         "https://www.forexlive.com/feed/news",
         "https://www.forexlive.com/feed/technicalanalysis",
         "https://www.forexlive.com/feed/forexorders",
         "https://www.forexlive.com/feed/centralbank",
         "https://www.forexlive.com/feed/education",
         "https://www.forexlive.com/feed/cryptocurrency",
         "https://www.thehindu.com/feeder/default.rss",
         "https://www.thehindu.com/news/feeder/default.rss",
         "https://www.thehindu.com/news/national/feeder/default.rss",
         "https://www.thehindu.com/news/international/feeder/default.rss",
         "https://www.thehindu.com/news/states/feeder/default.rss",
         "https://www.thehindu.com/news/cities/feeder/default.rss",
         "https://www.thehindu.com/opinion/feeder/default.rss",
         "https://www.thehindu.com/opinion/columns/feeder/default.rss",
         "https://www.thehindu.com/opinion/op-ed/feeder/default.rss",
         "https://www.thehindu.com/opinion/editorial/feeder/default.rss",
         "https://www.thehindu.com/opinion/interview/feeder/default.rss",
         "https://www.thehindu.com/business/feeder/default.rss",
         "https://www.thehindu.com/business/agri-business/feeder/default.rss",
         "https://www.thehindu.com/business/Industry/feeder/default.rss",
         "https://www.thehindu.com/business/Economy/feeder/default.rss",
         "https://www.thehindu.com/business/markets/feeder/default.rss",
         "https://www.thehindu.com/business/budget/feeder/default.rss",
         "https://www.thehindu.com/business/feeder/default.rss",
         "https://www.thehindu.com/business/agri-business/feeder/default.rss",
         "https://www.thehindu.com/business/Industry/feeder/default.rss",
         "https://www.thehindu.com/business/Economy/feeder/default.rss",
         "https://www.thehindu.com/business/markets/feeder/default.rss",
         "https://www.thehindu.com/business/budget/feeder/default.rss",
         # "https://www.thehindu.com/sport/feeder/default.rss",
         # "https://www.thehindu.com/sport/cricket/feeder/default.rss",
         # "https://www.thehindu.com/sport/football/feeder/default.rss",
         # "https://www.thehindu.com/sport/athletics/feeder/default.rss",
         # "https://www.thehindu.com/sport/other-sports/feeder/default.rss",
         # "https://www.thehindu.com/sci-tech/science/feeder/default.rss",
         # "https://www.thehindu.com/life-and-style/feeder/default.rss",
         # "https://www.thehindu.com/life-and-style/motoring/feeder/default.rss",
         # "https://www.thehindu.com/life-and-style/travel/feeder/default.rss",
         # "https://www.thehindu.com/life-and-style/homes-and-gardens/feeder/default.rss",
         "https://www.biometricupdate.com/feed",
         "https://www.pymnts.com/feed/",
         "https://www.nation.com.pk/rss/blogs",
         "https://www.nation.com.pk/rss/breaking-news",
         "https://www.nation.com.pk/rss/business",
         # "https://www.nation.com.pk/rss/education",
         "https://www.nation.com.pk/rss/events",
         "https://www.nation.com.pk/rss/headlines",
         "https://www.nation.com.pk/rss/international",
         # "https://www.nation.com.pk/rss/lifestyle-entertainment",
         # "https://www.nation.com.pk/rss/multimedia",
         "https://www.nation.com.pk/rss/national",
         "https://www.nation.com.pk/rss/newspaper",
         "https://www.nation.com.pk/rss/opinions",
         "https://www.nation.com.pk/rss/politics",
         "https://www.nation.com.pk/rss/regional",
         # "https://www.nation.com.pk/rss/sports",
         # "https://www.nation.com.pk/rss/technology",
         "https://www.bis.org/doclist/rss_all_categories.rss",
         "https://www.bis.org/doclist/all_pressrels.rss",
         # "https://www.bis.org/doclist/vacancies.rss",
         "https://www.bis.org/doclist/bis_fsi_publs.rss",
         "https://www.bis.org/doclist/cbspeeches.rss",
         "https://www.bis.org/doclist/mgmtspeeches.rss"]
