links = [
    'https://www.sc.com.my/XTOPIA_sitemap.ashx',
    'http://nbs.rs/sitemap.xml',
    'http://www.bot.or.th/en.sitemap.xml',
    'http://www.bot.or.th/th.sitemap.xml',
    'http://www.bundesfinanzministerium.de/sitemap.xml',
    'http://www.snb.ch/public/de/seo/sitemap.xml',
    'http://www.snb.ch/public/en/seo/sitemap.xml',
    'http://www.snb.ch/public/fr/seo/sitemap.xml',
    'http://www.snb.ch/public/it/seo/sitemap.xml',
    'https://ai.gov/sitemap.xml',
    'https://cbu.uz/en/sitemap.xml',
    'https://cbu.uz/oz/sitemap.xml',
    'https://cbu.uz/ru/sitemap.xml',
    'https://cbu.uz/uz/sitemap.xml',
    'https://commission.europa.eu/sitemap.xml',
    'https://finance.yahoo.com/sitemap_en-us_desktop_index.xml',
    # 'https://finance.yahoo.com/sitemap_en-us_quotes_index.xml',
    'https://finance.yahoo.com/sitemaps/finance-sitemap_googlenewsindex_US_en-US.xml.gz',
    'https://finance.yahoo.com/sitemaps/finance-sitemap_index_US_en-US.xml.gz',
    # 'https://lenta.ru/sitemap.xml.gz',# обновляются /persons/ у миллиона примерно за 30 минут
    'https://nbg.gov.ge/sitemap.xml',
    'https://www.acm.nl/sitemap.xml',
    'https://www.amf-france.org/sitemap.xml',
    'https://www.ascionline.in/sitemap.xml',
    'https://www.bankofcanada.ca/wp-sitemap.xml',
    'https://www.bankofengland.co.uk/_api/sitemap/getsitemap',
    'https://www.bc.gob.cu/sitemap.xml',
    'https://www.bis.org/sitemap.xml',
    'https://www.bmf.gv.at/sitemap.xml',
    'https://www.bundesbank.de/service-sitemap-01a59a5d5e114f25a9a55e26583069ec-sitemap_index.xml',
    'https://www.bundesbank.de/service-sitemap-34041d60a21884ad31dcd7976ab01d50-sitemap_index.xml',
    'https://www.bundestag.de/service-sitemap-bundestagde-sitemap_index.xml',
    'https://www.bundestag.de/service-sitemap-bundestagen-sitemap_index.xml',
    'https://www.bundestag.de/service-sitemap-bundestagfr-sitemap_index.xml',
    'https://www.bundestag.de/service-sitemap-webarchiv-sitemap_index.xml',
    'https://www.centralbank.ie/sitemap/sitemap.xml',
    'https://www.chinabankingnews.com/sitemap_index.xml',
    'https://www.dfsa.ae/sitemap.xml',
    'https://www.dnb.nl/en/sitemap.xml',
    'https://www.dnb.nl/sitemap.xml',
    'https://www.ebf.eu/sitemap_index.xml',
    'https://www.ecb.europa.eu/sitemap.xml',
    'https://www.eccb-centralbank.org/sitemap.xml',
    'https://www.eftasurv.int/cms/api/sitemap',
    # 'https://www.eib.org/sitemaps-de.xml',
    'https://www.eib.org/sitemaps-en.xml',
    # 'https://www.eib.org/sitemaps-fr.xml',
    'https://www.eiopa.europa.eu/sitemap.xml',
    'https://www.fca.org.uk/sitemap.xml',
    'https://www.fdic.gov/sitemap.xml',
    'https://www.finanssivalvonta.fi/sitemap.xml',
    'https://www.fstb.gov.hk/sitemaps/fstb_legco.xml',
    'https://www.fstb.gov.hk/sitemaps/fstb_press.xml',
    'https://www.fstb.gov.hk/sitemaps/fstb_speech.xml',
    'https://www.fstb.gov.hk/sitemaps/fstb_transcript.xml',
    'https://www.fstb.gov.hk/sitemaps/tb_legco_bill.xml',
    'https://www.fstb.gov.hk/sitemaps/tb_legco_debate.xml',
    'https://www.fstb.gov.hk/sitemaps/tb_legco_q.xml',
    'https://www.fstb.gov.hk/sitemaps/tb_press.xml',
    'https://www.fstb.gov.hk/sitemaps/tb_speech.xml',
    'https://www.fstb.gov.hk/sitemaps/tb_transcript.xml',
    'https://www.gov.br/sitemap.xml.gz',
    'https://www.gov.uk/sitemap.xml',
    'https://www.imda.gov.sg/-/media/sitemap/sitemap.xml',
    'https://www.irs.gov/sitemap.xml',
    'https://www.openbanking.qa/sitemap_index.xml',
    # 'https://www.prnewswire.com/ae/ar/sitemap-news.xml',
    # 'https://www.prnewswire.com/ae/ar/sitemap.xml',
    # 'https://www.prnewswire.com/ae/sitemap-news.xml',
    # 'https://www.prnewswire.com/ae/sitemap.xml',
    # 'https://www.prnewswire.com/apac/sitemap-news.xml',
    # 'https://www.prnewswire.com/apac/sitemap.xml',
    # 'https://www.prnewswire.com/cs/sitemap-news.xml',
    # 'https://www.prnewswire.com/cs/sitemap.xml',
    # 'https://www.prnewswire.com/da/sitemap-news.xml',
    # 'https://www.prnewswire.com/da/sitemap.xml',
    # 'https://www.prnewswire.com/de/sitemap-news.xml',
    # 'https://www.prnewswire.com/de/sitemap.xml',
    # 'https://www.prnewswire.com/es/sitemap-news.xml',
    # 'https://www.prnewswire.com/es/sitemap.xml',
    # 'https://www.prnewswire.com/fi/sitemap-news.xml',
    # 'https://www.prnewswire.com/fi/sitemap.xml',
    # 'https://www.prnewswire.com/fr/sitemap-news.xml',
    # 'https://www.prnewswire.com/fr/sitemap.xml',
    # 'https://www.prnewswire.com/il/sitemap-news.xml',
    # 'https://www.prnewswire.com/il/sitemap.xml',
    # 'https://www.prnewswire.com/in/sitemap-news.xml',
    # 'https://www.prnewswire.com/in/sitemap.xml',
    # 'https://www.prnewswire.com/it/sitemap-news.xml',
    # 'https://www.prnewswire.com/it/sitemap.xml',
    # 'https://www.prnewswire.com/nl/sitemap-news.xml',
    # 'https://www.prnewswire.com/nl/sitemap.xml',
    # 'https://www.prnewswire.com/no/sitemap-news.xml',
    # 'https://www.prnewswire.com/no/sitemap.xml',
    # 'https://www.prnewswire.com/pl/sitemap-news.xml',
    # 'https://www.prnewswire.com/pl/sitemap.xml',
    # 'https://www.prnewswire.com/pt/sitemap-news.xml',
    # 'https://www.prnewswire.com/pt/sitemap.xml',
    'https://www.prnewswire.com/ru/sitemap-news.xml',
    'https://www.prnewswire.com/ru/sitemap.xml',
    'https://www.prnewswire.com/sitemap-news.xml',
    'https://www.prnewswire.com/sitemap.xml',
    # 'https://www.prnewswire.com/sk/sitemap-news.xml',
    # 'https://www.prnewswire.com/sk/sitemap.xml',
    # 'https://www.prnewswire.com/sv/sitemap-news.xml',
    # 'https://www.prnewswire.com/sv/sitemap.xml',
    'https://www.psr.org.uk/sitemap.xml',
    'https://www.rbc.ru/sitemap_index.xml',
    'https://www.resbank.co.za/en.sitemap.xml',
    'https://www.sca.gov.ae/sitemap.xml',
    'https://www.scb.gov.bs/wp-sitemap.xml',
    'https://www.sec.gov.ph/sitemap_index.xml',
    'https://www.whitehouse.gov/es/sitemap_index.xml',
    'https://www.whitehouse.gov/sitemap_index.xml',
    'https://www.worldbank.org/sitemap.xml',
    'https://www.bcra.gob.ar/Varios/sitemap.xml',
    'https://www.abnrlaw.com/sitemap.xml',

    'https://www.wsbi-esbg.org/sitemap_index.xml',
    'https://boj.org.jm/sitemap_index.xml',
    'https://www.securities-administrators.ca/sitemap_index.xml',

]
