# docker build -t scheduler -f Dockerfile-scheduler .
# docker run --name scheduler scheduler
# docker stop scheduler
# docker rm scheduler
FROM python:3.8-slim

WORKDIR /app

COPY ../../requirements.txt ./requirements.txt

RUN pip3 install --no-cache-dir --upgrade pip \
 && pip3 install --no-cache-dir --upgrade pip setuptools wheel

RUN pip3 install --no-cache-dir -r ./requirements.txt

COPY ./src/ml/scheduler.py /app/src/ml/scheduler.py
COPY ./src/backend/models.py /app/src/backend/models.py

CMD ["python3", "-m", "src.ml.scheduler"]