#uses duckduckgo_search
def generate_links() -> list:
    source_names = ["Правительство Австралии - The Australian or Commonwealth Government ",
                    "Резервный Банк Австралии - Reserve Bank of Australia ",
                    "Австралийская комиссия по ценным бумагам и инвестициям - Australian Securities and Investments Commission ",
                    "Австралийская комиссия по конкуренции и защите прав потребителей - Australian Competition and Consumer Commission ",
                    "Австралийская администрация регулирования с совещательным правом - Australian Prudential Regulation Authority ",
                    "Подразделение финансовой разведки Австралии - Australian Transaction Reports and Analysis Centre ",
                    "Казначейство Австралии - Department of Treasury and Finance ",
                    "Министерство финансов Австрии - Austrian Federal Ministry of Finance ",
                    "Австрийское Казначейство - Austrian Treasury / Österreichische Bundesfinanzierungsagentur ",
                    "Банк Австрии - Bank Austria / Oesterreichische Nationalbank ",
                    "Правительство Аргентины - Government of Argentina ",
                    "Федеральное управление государственных доходов Аргентины - Argentina’s Federal Administration of Public Revenue ",
                    "Центральный банк Аргентины - Central Bank of the Argentine Republic ",
                    "Министерство экономики Аргентины - Ministry of Economy of Argentina ",
                    "Национальная комиссия по ценным бумагам Аргентины - Consultas Publicas Vigentes ",
                    "Центральный банк Азербайджана - Central Bank of the Republic of Azerbaijan ",
                    "Центральный банк Афганистана - Da Afghanistan Bank ",
                    "Центральный банк Багамских островов - The Central Bank of The Bahamas  ",
                    "Правительство Багамских островов - Government of the Commonwealth of the Bahamas ",
                    "Комиссия по ценным бумагам Багамских островов - Securities Commission of The Bahamas ",
                    "Национальный банк Республики Беларусь - National Bank of the Republic of Belarus ",
                    "Центральный банк Бразилии - The Central Bank of Brazil ",
                    "Комиссия по ценным бумагам Бразилии - The Securities and Exchange Commission of Brazil ",
                    "Федеральная налоговая служба Бразилии - The Brazilian Federal Revenue Department ",
                    "Банк Англии - Bank of England ",
                    "Министерство финансов Великобритании - The Ministry of Finance ",
                    "Регулятор платежных систем Великобритании - Payment Systems Regulator ",
                    "Управление по защите конкуренции и рынкам - The Competition and Markets Authority ",
                    "Упpaвлeниe пo cтaндapтaм peклaмы Beликoбpитaнии - The Advertising Standards Authority ",
                    "Управление по финансовому регулированию и надзору Великобритании - Financial Conduct Authority ",
                    "Управлением пруденциального надзора - Prudential Regulation Authority ",
                    "Подразделение по цифровым рынкам - Digital Markets Unit ",
                    "Центральный банк Ирландии - The Central Bank of Ireland ",
                    "Open Banking Implementation Entity - перевода нет ",
                    "Комитет по финансовой политике Банка Англии - The Bank of England’s Financial Policy Committee ",
                    "Общепартийная парламентская группа Великобритании по криптовалютам и цифровым активам - The All Party Parliamentary Group on Digital Regulation and Responsibility ",
                    "Служба по вопросам выполнения финансовых санкций - Office of Financial Sanctions Implementation HM Treasury ",
                    "Комитет цифрового развития, культуры, СМИ и спорта Парламента Великобритании - Department for Digital, Culture, Media & Sport ",
                    "Правительство Великобритании - His Majesty's Government / the Government of the United Kingdom ",
                    "Центральный банк Венгрии - the National Bank of Hungary ",
                    "Восточно-Карибский Центральный банк - Eastern Caribbean Central Bank ",
                    "Правительство Венесуэлы - Government of Venezuela ",
                    "Центральный банк Венесуэлы - Central Bank of Venezuela ",
                    "Государственный банк Вьетнама - State Bank of Vietnam ",
                    "Банк Ганы - Bank of Ghana ",
                    "Немецкий федеральный банк - Deutsche Bundesbank ",
                    "Немецкий федеральный банк - Deutsche Bundesbank ",
                    "Парламент Германии - German Bundestag ",
                    "Федеральное управление финансового надзора Германии - The Federal Financial Supervisory Authority ",
                    "Федеральное министерство финансов Германии - Bundesministerium der Finanzen ",
                    "Бюро финансовых услуг и казначейства Гонконга - Financial Services and the Treasury Bureau ",
                    "Денежно-кредитное управление Гонконга - Hong Kong Monetary Authority ",
                    "Комиссия по ценным бумагам и фьючерсам Гонконга - The Securities and FuturesCommission of Hong Kong ",
                    "Казначейство Гонконга - The Hong Kong Monetary Authority ",
                    "Парламент Гонконга - Legislative Council of Hong Kong ",
                    "Национальный банк Грузии - National Bank of Georgia ",
                    "Правительство Доминики - The Government of the Commonwealth of Dominica ",
                    "Европарламент - European Parliament ",
                    "Европейская инспекция по защите данных - The European Data Protection Supervisor ",
                    "Европейская служба банковского надзора - The European Banking Authority ",
                    "Eвpoпeйcкaя cлyжбa cтpaxoвaния и пeнcиoннoгo oбecпeчeния - The European Insurance and Occupational Pensions Authority ",
                    "Европейский инвестиционный банк - European investment bank ",
                    "Европейский совет по защите данных - European Data Protection Board ",
                    "Европейский центральный банк - European Central Bank ",
                    "Европейское управление по ценным бумагам и рынкам - The European Securities and Markets Authority ",
                    "Совет ЕС - The European Council ",
                    "Европейские надзорные органы - The EFTA Surveillance Authority ",
                    "Европейская комиссия - The European Commission ",
                    "Агентство Европейского Союза по сотрудничеству в области уголовного правосудия - The European Union Agency for Criminal Justice Cooperation ",
                    "Комитет по экономическим и валютным вопросам Европейского парламента - The European Parliament's Committee on Economic and Monetary Affairs ",
                    "Европейская организация по защите прав потребителей - The European Consumer Organisation ",
                    "Европейская банковская федерация - The European Banking Federation ",
                    "Европейский союз сберегательных и розничных банков - The European Savings and Retail Banking Group ",
                    "Центральный банк Египта - The Central Bank of Egypt ",
                    "Резервный банк Зимбабве - The Reserve Bank of Zimbabwe ",
                    "Банк Израиля - The Bank of Israel ",
                    "Комиссия по ценным бумагам Израиля - Israel Securities Authority ",
                    "Налоговое управление Израиля - Israel Tax Authority ",
                    "Управление по ценным бумагам Израиля - Israel Securities Authority ",
                    "Комиссия по конкуренции Индии - Competition Commission of India ",
                    "Министерство по корпоративным вопросам Индии - The Ministry of Corporate Affairs ",
                    "Министерство электроники и информационных технологий Индии - The Ministry of Electronics and Information Technology of the Republic of India ",
                    "Резервный банк Индии - Reserve Bank of India ",
                    "Национальная платежная корпорация Индии - National Payments Corporation of India ",
                    "Правительство Индии - The Government of India ",
                    "Совет по стандартам рекламы Индии - The Advertising Standards Council of India ",
                    "Центральный банк Индонезии - Central Bank of Indonesia ",
                    "Агентство по регулированию торговли товарными фьючерсами Индонезии - The Commodity and Futures Trading Regulatory Agency ",
                    "Министерство промышленности и торговли Ирана - The Ministry of Industry, Mine and Trade ",
                    "Центральный Банк Ирана - Central Bank of the Islamic Republic of Iran, Bank Markazi ",
                    "Организация по сбору и продаже государственного имущества Ирана - he Organization for Collection and Sale of State-Owned Property ",
                    "Центральный банк Ирландии - The Central Bank of Ireland ",
                    "Министерство финансов Испании -  Ministry of Economic Affairs and Digital Transformation ",
                    "Налоговая служба Испании - Spanish Tax Agency / Agencia Estatal de Administración Tributaria ",
                    "Национальная комиссия по рынку ценных бумаг Испании - The National Securities Market Commission of Spain ",
                    "Центральный банк Испании - The Bank of Spain ",
                    "Антимонопольное управление Италии - The Italian Competition Authority ",
                    "Ассоциация банков Италии - Italian banking association / Associazione Bancaria Italiana ",
                    "Министерство экономики и финансов Италии - Ministry of Economy and Finance of Italy ",
                    "Банк Канады – Bank of Canada ",
                    "Организация по регулированию инвестиционной отрасли Канады - Investment Industry Regulatory Organization of Canada ",
                    "Правительство Канады - The federal government of Canada ",
                    "Управление по ценным бумагам Канады - The Canadian Securities Administrators ",
                    "Центр анализа финансовых операций и отчетности Канады - The Financial Transactions and Reports Analysis Centre of Canada ",
                    "Администрация киберпространства Китая - The Cyberspace Administration of China ",
                    "Антимонопольный комитет Государственного совета Китая - The Anti-Monopoly Committee of the State Council ",
                    "Банковская ассоциация Китая - China Banking Association ",
                    "Государственное валютное управление - The State Administration of Foreign Exchange People's Republic of China ",
                    "Государственное управление по регулированию рынка КНР - State Administration for Market Regulation ",
                    "Китайская академия общественных наук - The Chinese Academy of Social Sciences ",
                    "Комиссия по регулированию банковской и страховой деятельности Китая - The China Banking and Insurance Regulatory Commission ",
                    "Комиссия по регулированию ценных бумаг Китая - The China Securities Regulatory Commission ",
                    "Министерство промышленности и информационных технологий Китая - Ministry of Industry and Information Technology of the People's Republic of China ",
                    "Народный банк Китая (НБК) – People’s Bank of China ",
                    "Национальная ассоциация интернет-финансов Китая - The National Internet Finance Association of China ",
                    "Национальная блокчейн-сеть Китая - China’s National Blockchain Service Network ",
                    "Национальная комиссия по развитию и реформам Китая - National Development and Reform Commission of the People's Republic of China ",
                    "Платежно-клиринговая ассоциация Китая - The Payment & Clearing Association of China ",
                    "Постоянный комитет Всекитайского собрания народных представителей - The Standing Committee of the National People's Congress of the People's Republic of China ",
                    "Почтовый сберегательный банк Китая - Postal Savings Bank of China ",
                    "Управление по контролю за рынком Китая - The State Administration for Market Supervision ",
                    "Центральный банк Колумбии - The Bank of the Republic ",
                    "Королевское валютное управление Бутана - Royal Monetary Authority of Bhutan ",
                    "Правительство Бутана - Royal Government of Bhutan ",
                    "Центральный банк Кубы - The Central Bank of Cuba / Banco Central de Cuba ",
                    "Национальный банк Кыргызской Республики – The National Bank Of the Kyrgyz Republic ",
                    "Правительство Литвы - The Government of Lithuania ",
                    "Национальная комиссия Люксембурга по защите данных - The National Commission for Data Protection ",
                    "Центральный банк Маврикия - State Bank of Mauritius ",
                    "Центральный банк Малайзии - Банк Негара Малайзии - Bank Negara Malaysia ",
                    "Комиссия по ценным бумагам Малайзии - The Securities Commission Malaysia ",
                    "Пpaвитeльcтвo нaциoнaльнoгo eдинcтвa - The National Unity Government of the Republic of the Union of Myanmar ",
                    "Азиатский банк развития - The Asian Development Bank ",
                    "Арабский валютный фонд - The Arab Monetary Fund ",
                    "Базельский комитет по банковскому надзору (БКБН) - The Basel Committee on Banking Supervision ",
                    "Восточно-Карибский Центральный банк - The Eastern Caribbean Central Bank ",
                    "Всемирный банк - The World Bank ",
                    "Группа разработки финансовых мер по борьбе с отмыванием денег (ФАТФ) - Financial Action Task Force ",
                    "Детский фонд Организации Объединенных Наций (ЮНИСЕФ) - United Nations Children's Fund ",
                    "Банк международных расчетов (БМР) - Bank for International Settlements ",
                    "Комитет по платежам и рыночным инфраструктурам - Committee on Payments and Market Infrastructures ",
                    "Межбанковская система передачи финансовых сообщений SWIFT - The Society of Worldwide Interbank Financial Telecommunication ",
                    "Международная ассоциация свопов и деривативов - International Swaps and Derivatives Association ",
                    "Международная организация комиссий по ценным бумагам - International Organization of Securities Commissions ",
                    "Международный валютный фонд - The International Monetary Fund ",
                    "Совет по финансовой стабильности (СФС) - Financial Stability Board ",
                    "Министерство финансов - The Secretariat of the Treasury and Public Credit / Secretaría de Hacienda y Crédito Público ",
                    "Национальная комиссия по банкам и ценным бумагам - National Banking and Securities Commission ",
                    "Банк Мексики - The Bank of Mexico / Banco de México ",
                    "Комиссия Молдавии по чрезвычайным ситуациям - The Commission for Emergency Situations ",
                    "Центральный банк Намибии - The Bank of Namibia ",
                    "Банк Нигерии - Central Bank of Nigeria ",
                    "Комиссия по ценным бумагам и биржам Нигерии - The Securities and Exchange Commission of Nigeria ",
                    "Управление по делам потребителей и рынков Нидерландов - Netherlands Authority for Consumers and Markets ",
                    "Центральный банк Нидерландов - Central Bank of the Netherlands / De Nederlandsche Bank ",
                    "Служба финансовой разведки и расследований Нидерландов - Fiscale inlichtingen-en opsporingsdienst ",
                    "Управления по финансовым рынкам Нидерландов - The Dutch Authority for the Financial Market ",
                    "Резервный банк Новой Зеландии - Reserve Bank of New Zealand ",
                    "Управление финансовых рынков Новой Зеландии - Financial Markets Authority of New Zealand ",
                    "Центральный банк ОАЭ - Central Bank of the United Arab Emirates ",
                    "Управление по регулированию рынков финансовых услуг Международного финансового центра Абу-Даби - Abu Dhabi Global Market’s (ADGM’s) Financial Services Regulatory Authority ",
                    "Международный финансовый центр Абу-Даби - Abu Dhabi Global Market’s ",
                    "Служба надзора за финансовыми услугами Дубая - The Dubai Financial Services Authority ",
                    "Управление по регулированию виртуальных активов Дубая - The Virtual Assets Regulatory Authority ",
                    "Управление по ценным бумагам и сырьевым товарам ОАЭ - The Emirates Securities and Commodities Authority ",
                    "Управление по рынку капитала Омана - The Capital Market Authority of Oman ",
                    "Государственный банк Пакистана - State Bank of Pakistan ",
                    "Правительство Пакистана - The Government of Pakistan ",
                    "Национальная администрация электроэнергетики Парагвая - The National Electricity Administration of Paraguay ",
                    "Национальная комиссия по ценным бумагам Парагвая - National Securities Commission of Paraguay ",
                    "Центральный резервный банк Перу - Banco Central de Reserva del Perú / The Central Reserve Bank of Peru ",
                    "Центральный банк Саудовской Аравии  - The Saudi Central Bank ",
                    "Национальный банк Сербии - The National Bank of Serbia ",
                    "Денежно-кредитное управление Сингапура - Monetary Authority of Singapore ",
                    "Государственное агентство Сингапура - Infocomm Media Development Authority ",
                    "Центральный банк Судана -The Central Bank of Sudan ",
                    "Комиссии по ценным бумагам и биржам США - U.S. Securities and Exchange Commission ",
                    "Налоговая служба США - Налоговое управление США – U.S. Internal Revenue Service ",
                    "Национальное управление кредитных союзов США – U.S. National Credit Union Administration ",
                    "Национальный консультативный комитет по искусственному интеллекту - The National Ai Advisory Committee ",
                    "Рабочая группа по финансовым рынкам при Президенте США - The President's Working Group on Financial Markets ",
                    "Сеть по борьбе с финансовыми преступлениями США - The Financial Crimes Enforcement Network ",
                    "Управление контролера денежного обращения США - Office of the Comptroller of the Currency ",
                    "Федеральная резервная система США - U.S. Federal Reserve System ",
                    "Федеральная корпорация страхования вкладов - The Federal Deposit Insurance Corporation ",
                    "Американское Национальное бюро некоммерческих исследований - The National Bureau of Economic Research ",
                    "Федеральный комитет по операциям на открытом рынке ФРС США - The Federal Open Market Committee ",
                    "Управление научной и технической политики при Президенте США- The Office of Science and Technology Policy ",
                    "Управление по контролю за иностранными активами Министерства финансов США - The Office of Foreign Assets Control  ",
                    "Департамент финансовых услуг штата Нью-Йорк - The New York State Department of Financial Services ",
                    "Департамент финансовой защиты и инноваций Калифорнии - The California Department of Financial Protection and Innovation ",
                    "Комиссия по справедливым политическим практикам Калифорнии - The Fair Political Practices Commission of California ",
                    "Федеральное бюро расследований США - The Federal Bureau of Investigation ",
                    "Департамент доходов штата Колорадо (США) - The Colorado Department of Revenue ",
                    "Совет по надзору за финансовой стабильностью США – The Financial Stability Oversight Council ",
                    "Комиссии по торговле товарными фьючерсами – The  Commodity Futures Trading Commission ",
                    "Министерство финансов США - The Department of the Treasury ",
                    "Служба регулирования сектора финансовых услуг США - The Financial Industry Regulatory Authority ",
                    "Федеральный резервный банк (ФРБ) Нью-Йорка - The Federal Reserve Bank of New York ",
                    "Комитет по финансовым услугам Палаты представителей США - The Financial Services Committee ",
                    "Палата представителей штата Техас (США) - The Texas House of Representatives ",
                    "Совет экономических консультантов при Президенте США - The Council of Economic Advisers ",
                    "Федеральный резервный банк Чикаго - The Federal Reserve Bank of Chicago ",
                    "Банк Таиланда - Bank of Thailand ",
                    "Комиссия по ценным бумагам и биржам Таиланда - Securities and Exchange Commission of Thailand ",
                    "Министерство финансов Таиланда - The Ministry of Finance ",
                    "Комиссия по финансовому надзору Тайваня - The Financial Services Commission ",
                    "Центральный банк Тайваня - The Central Bank of the Republic of China (Taiwan) ",
                    "Банк Танзании – The Bank of United Republic of Tanzania ",
                    "Центральный банк Туниса - The Central Bank of Tunisia ",
                    "Министерство финансов Турции - The Ministry of Treasury and Finance ",
                    "Центральный банк Турции (Турецкой Республики) – The Central Bank of the Republic of Turkey ",
                    "Банк Уганды - The Bank of Uganda ",
                    "Центральный банк Республики Узбекистан – The Central Bank of the Republic of Uzbekistan ",
                    "Национальное агентство перспективных проектов Узбекистана - National Agency of Perspective Projects of the Republic of Uzbekistan ",
                    "Национальный банк Украины – The National Bank of Ukraine ",
                    "Центральный банк Уругвая - The Central Bank of Uruguay / Banco Central del Uruguay ",
                    "Правительство Уругвая - The Government of Uruguay ",
                    "Центральный банк Филиппин - Philippine National Bank / The Bangko Sentral ng Pilipina ",
                    "Комиссия по ценным бумагам и биржам Филиппин - The Securities and Exchange Commission ",
                    "Управление по финансовому надзору Финляндии - The Finnish Financial Supervisory Authority ",
                    "Банк Франции - The Bank of France ",
                    "Управление по вопросам конкуренции Франции - The French Competition Authority ",
                    "Управления по финансовым рынкам Франции - Financial Markets Regulator / Autorité des marchés financiers ",
                    "Служба по надзору за финансовыми рынками Швейцарии - Financial Market Supervisory Authority ",
                    "Национальный банк Швейцарии - Swiss National Bank ",
                    "Швейцарская комиссия по конкуренции - The Swiss Competition Commission ",
                    "Управление финансового надзора Швеции - Financial Supervisory Authority of Sweden ",
                    "Центральный банк Шри-Ланки - The Central Bank of Sri Lanka ",
                    "Управление по регулированию и контролю финансового сектора Южной Африки - The Financial Sector Conduct Authority ",
                    "Южно-Африканский резервный банк - South African Reserve Bank ",
                    "Совет по регулированию рекламы ЮАР - Advertising Regulatory Board ",
                    "Банк Кореи - The Bank of Korea ",
                    "Комиссия по справедливой торговле Южной Кореи - Korea Fair Trade Commission ",
                    "Комиссия по финансовым услугам Южной Кореи - The Financial Services Commission ",
                    "Налоговая служба Южной Кореи - The National Tax Service ",
                    "Служба финансового надзора Южной Кореи - Financial Supervisory Service ",
                    "Министерство стратегии и финансов Южной Кореи - The Ministry of Economy and Finance ",
                    "Министерство юстиции Южной Кореи - South Korea's Ministry of Justice ",
                    "Банк Ямайки – The Bank of Jamaika ",
                    "Агентство по финансовым услугам Японии - The Financial Services Agency ",
                    "Банк Японии – The Bank of Japan ",
                    ]
    source_links = []
    from duckduckgo_search import DDGS

    ddgs = DDGS(timeout=6000)

    for i in range(len(source_links), len(source_names)):
        results = ddgs.text(source_names[i], max_results=1, backend="html")
        for j in results:
            source_links.append(j['href'])
        if i % 5 == 0:
            print(i / len(source_names))
    return source_links

source_links_computed = ['https://en.wikipedia.org/wiki/Australian_Government',
 'https://www.rba.gov.au/',
 'https://asic.gov.au/',
 'https://www.accc.gov.au/',
 'https://www.apra.gov.au/',
 'https://www.austrac.gov.au/',
 'https://www.dtf.vic.gov.au/home',
 'https://www.bmf.gv.at/en.html',
 'https://www.oebfa.at/en/ueber-die-oebfa.html',
 'https://www.oenb.at/en/',
 'https://en.wikipedia.org/wiki/Government_of_Argentina',
 'https://www.afip.gob.ar/landing/default.asp',
 'https://www.bcra.gob.ar/Varios/English_information.asp',
 'https://www.economia.gob.ar/en/',
 'https://www.nssmc.gov.ua/',
 'https://www.cbar.az/home?language=en',
 'https://dab.gov.af/',
 'https://www.centralbankbahamas.com/',
 'https://www.bahamas.gov.bs/wps/portal/public',
 'https://www.scb.gov.bs/',
 'https://www.nbrb.by/',
 'https://www.bcb.gov.br/en',
 'https://www.gov.br/cvm/en',
 'https://www.gov.br/receitafederal/en',
 'https://www.bankofengland.co.uk/',
 'https://www.gov.uk/government/organisations/hm-treasury',
 'https://www.psr.org.uk/',
 'https://en.wikipedia.org/wiki/Competition_and_Markets_Authority',
 'https://en.wikipedia.org/wiki/Advertising_Standards_Authority_(United_Kingdom)',
 'https://www.fca.org.uk/',
 'https://www.bankofengland.co.uk/prudential-regulation',
 'https://www.gov.uk/government/collections/digital-markets-unit',
 'https://www.centralbank.ie/',
 'https://www.openbanking.org.uk/about-us/',
 'https://www.bankofengland.co.uk/about/people/financial-policy-committee',
 'https://www.rbc.ru/crypto/news/647dc88e9a7947f6426d75e8',
 'https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation',
 'https://committees.parliament.uk/committee/378/digital-culture-media-and-sport/role',
 'https://en.wikipedia.org/wiki/Government_of_the_United_Kingdom',
 'https://www.mnb.hu/en/',
 'https://www.eccb-centralbank.org/',
 'https://en.wikipedia.org/wiki/Government_of_Venezuela',
 'https://en.wikipedia.org/wiki/Central_Bank_of_Venezuela',
 'https://www.sbv.gov.vn/webcenter/portal/en/home/sbv',
 'https://www.bog.gov.gh/',
 'https://www.bundesbank.de/en',
 'https://www.bundesbank.de/en',
 'https://www.bundestag.de/en',
 'https://www.bafin.de/EN/Homepage/homepage_node.html',
 'https://www.bundesfinanzministerium.de/Web/EN/Home/home.html',
 'https://www.fstb.gov.hk/en/',
 'https://www.hkma.gov.hk/eng/key-functions/money/',
 'https://finansistem.com/hkg/',
 'https://www.hkma.gov.hk/eng/',
 'https://en.wikipedia.org/wiki/Legislative_Council_of_Hong_Kong',
 'https://nbg.gov.ge/en',
 'https://dominica.gov.dm/',
 'https://www.europarl.europa.eu/portal/en',
 'https://www.edps.europa.eu/_en',
 'https://www.eba.europa.eu/homepage',
 'https://www.eiopa.europa.eu/index_en',
 'https://www.eib.org/en/index',
 'https://www.edpb.europa.eu/edpb_en',
 'https://www.ecb.europa.eu/',
 'https://www.esma.europa.eu/',
 'https://www.consilium.europa.eu/en/council-eu/',
 'https://www.eftasurv.int/',
 'https://commission.europa.eu/index_en',
 'https://www.eurojust.europa.eu/',
 'https://www.europarl.europa.eu/committees/en/econ/home/highlights',
 'https://en.wikipedia.org/wiki/The_European_Consumer_Organisation',
 'https://www.ebf.eu/',
 'https://www.wsbi-esbg.org/about-esbg/',
 'https://www.cbe.org.eg/',
 'https://www.rbz.co.zw/',
 'https://www.boi.org.il/en/',
 'https://www.isa.gov.il/sites/ISAEng/Pages/default.aspx',
 'https://www.gov.il/ru/departments/israel_tax_authority/govil-landing-page',
 'https://www.isa.gov.il/sites/ISAEng/Pages/default.aspx',
 'https://cci.gov.in/',
 'https://www.mca.gov.in/content/mca/global/en/home.html',
 'https://www.meity.gov.in/',
 'https://rbi.org.in/',
 'http://www.npci.org.in/',
 'https://en.wikipedia.org/wiki/Government_of_India',
 'https://www.ascionline.in/the-asci-code/',
 'https://www.bi.go.id/en/Default.aspx/',
 'https://www.abnrlaw.com/news/indonesias-commodities-futures-regulator-publishes-updated-list-of-approved-overseas-investments',
 'https://en.wikipedia.org/wiki/Ministry_of_Industry,_Mine_and_Trade',
 'https://cbi.ir/default_en.aspx',
 'https://en.wikipedia.org/wiki/Organization_for_Collection_and_Sale_of_State-owned_Properties_of_Iran',
 'https://www.centralbank.ie/',
 'https://portal.mineco.gob.es/en-us/Pages/default.aspx',
 'https://sede.agenciatributaria.gob.es/Sede/en_gb/inicio.html',
 'https://www.cnmv.es/portal/home.aspx?lang=en',
 'https://www.bde.es/wbe/en/',
 'https://en.agcm.it/en/',
 'https://www.abi.it/',
 'https://www.mef.gov.it/en/index.html',
 'https://www.bankofcanada.ca/',
 'https://www.iiroc.ca/',
 'https://www.canada.ca/en.html',
 'https://www.securities-administrators.ca/',
 'https://fintrac-canafe.canada.ca/intro-eng',
 'https://en.wikipedia.org/wiki/Cyberspace_Administration_of_China',
 'https://www.allbrightlaw.com/EN/10531/b3e2abc9161d4ee6.aspx',
 'http://www.afca-asia.org/Portal.do?method=memberDetailView&returnChannelID=29&resourceID=1',
 'https://www.safe.gov.cn/en/',
 'https://en.wikipedia.org/wiki/State_Administration_for_Market_Regulation',
 'http://casseng.cssn.cn/',
 'https://ru.wikipedia.org/wiki/Комиссия_по_регулированию_банковской_деятельности_Китая',
 'http://www.csrc.gov.cn/csrc_en/index.shtml',
 'https://en.wikipedia.org/wiki/Ministry_of_Industry_and_Information_Technology',
 'http://www.pbc.gov.cn/english/',
 'https://www.chinabankingnews.com/wiki/national-internet-finance-association-china-中国互联网金融协会/',
 'https://finance.yahoo.com/news/china-national-blockchain-change-world-182614309.html',
 'http://en.ndrc.gov.cn/',
 'https://www.prnewswire.com/news-releases/jianpu-technology-accepted-as-a-member-of-the-payment--clearing-association-of-china-301524913.html',
 "https://en.wikipedia.org/wiki/Standing_Committee_of_the_National_People's_Congress",
 'https://www.psbc.com/en/',
 'https://en.wikipedia.org/wiki/State_Administration_for_Market_Regulation',
 'https://www.banrep.gov.co/en',
 'https://www.rma.org.bt/',
 'https://www.pmo.gov.bt/',
 'https://www.bc.gob.cu/',
 'https://www.nbkr.kg/index.jsp?lang=ENG',
 'https://lrv.lt/en',
 'https://cnpd.public.lu/en.html',
 'https://bom.mu/',
 'https://ru.wikipedia.org/wiki/Банк_Негара_Малайзия',
 'https://www.sc.com.my/',
 'https://en.wikipedia.org/wiki/National_Unity_Government_of_Myanmar',
 'https://www.adb.org/',
 'https://www.amf.org.ae/en',
 'https://www.bis.org/bcbs/',
 'https://www.eccb-centralbank.org/',
 'https://www.worldbank.org/en/home',
 'https://ru.wikipedia.org/wiki/Группа_разработки_финансовых_мер_борьбы_с_отмыванием_денег',
 'https://www.unicef.org/',
 'https://www.bis.org/',
 'https://www.bis.org/cpmi/about/overview.htm',
 'https://lenta.ru/articles/2024/03/19/swift/',
 'https://www.isda.org/',
 'https://www.iosco.org/',
 'https://www.imf.org/en/home',
 'https://www.fsb.org/',
 'https://en.wikipedia.org/wiki/Secretariat_of_Finance_and_Public_Credit',
 'https://www.nssmc.gov.ua/en/',
 'https://www.banxico.org.mx/indexen.html',
 'https://dopomoga.gov.md/cse-24.06.2022',
 'https://www.bon.com.na/',
 'https://www.cbn.gov.ng/',
 'https://sec.gov.ng/',
 'https://www.acm.nl/en/about-acm/our-organization/the-netherlands-authority-for-consumers-and-markets',
 'https://www.dnb.nl/en/',
 'https://en.wikipedia.org/wiki/Fiscal_Information_and_Investigation_Service',
 'https://www.afm.nl/en/over-de-afm',
 'https://www.rbnz.govt.nz/',
 'https://www.fma.govt.nz/',
 'https://www.centralbank.ae/en',
 'https://www.adgm.com/financial-services-regulatory-authority',
 'https://www.adgm.com/',
 'https://www.dfsa.ae/',
 'https://www.vara.ae/en/',
 'https://www.sca.gov.ae/en/home.aspx',
 'https://cma.gov.om/',
 'https://www.sbp.org.pk/index.html',
 'https://en.wikipedia.org/wiki/Government_of_Pakistan',
 'https://en.wikipedia.org/wiki/ANDE_(Paraguay)',
 'https://www.nssmc.gov.ua/en/',
 'https://www.bcrp.gob.pe/',
 'https://www.sama.gov.sa/en-US/Pages/default.aspx',
 'https://www.nbs.rs/en/indeks/',
 'https://ru.wikipedia.org/wiki/Денежно-кредитное_управление_Сингапура',
 'https://www.imda.gov.sg/',
 'https://cbos.gov.sd/en',
 'https://www.sec.gov/',
 'https://www.irs.gov/ru/about-irs',
 'https://ncua.gov/',
 'https://ai.gov/naiac/',
 'https://home.treasury.gov/news/press-releases/jy0456',
 'https://www.fincen.gov/',
 'https://www.occ.treas.gov/',
 'https://www.federalreserve.gov/',
 'https://www.fdic.gov/',
 'https://www.nber.org/',
 'https://ru.wikipedia.org/wiki/Федеральный_комитет_по_операциям_на_открытом_рынке_ФРС_США',
 'https://www.whitehouse.gov/ostp/',
 'https://ofac.treasury.gov/',
 'https://ru.dfs.ny.gov/',
 'https://dfpi.ca.gov/',
 'https://www.fppc.ca.gov/',
 'https://ru.wikipedia.org/wiki/Федеральное_бюро_расследований',
 'https://cdor.colorado.gov/',
 'https://home.treasury.gov/policy-issues/financial-markets-financial-institutions-and-fiscal-service/fsoc',
 'https://www.cftc.gov/',
 'https://home.treasury.gov/',
 'https://www.finra.org/about',
 'https://www.newyorkfed.org/',
 'https://financialservices.house.gov/',
 'https://www.house.texas.gov/',
 'https://ru.wikipedia.org/wiki/Совет_экономических_консультантов',
 'https://www.chicagofed.org/',
 'https://www.bot.or.th/en/home.html',
 'https://www.sec.or.th/EN',
 'http://www2.mof.go.th/',
 'https://www.fsc.gov.tw/en/',
 'https://www.cbc.gov.tw/en/mp-2.html',
 'https://www.bot.go.tz/',
 'https://www.bct.gov.tn/bct/siteprod/index.jsp?la=AN',
 'https://en.hmb.gov.tr/',
 'https://www.tcmb.gov.tr/wps/wcm/connect/en/tcmb+en',
 'http://bou.or.ug/',
 'https://cbu.uz/en/',
 'https://www.napp.uz/en/',
 'https://bank.gov.ua/',
 'https://www.bcu.gub.uy/Paginas/Default.aspx',
 'https://en.wikipedia.org/wiki/Politics_of_Uruguay',
 'https://www.bsp.gov.ph/SitePages/Default.aspx',
 'https://www.sec.gov.ph/',
 'https://www.finanssivalvonta.fi/en',
 'https://www.banque-france.fr/en',
 'https://www.autoritedelaconcurrence.fr/en',
 'https://www.amf-france.org/en',
 'https://www.finma.ch/en',
 'https://www.snb.ch/en',
 'https://www.weko.admin.ch/weko/en/home.html',
 'https://fi.se/en/',
 'https://www.cbsl.gov.lk/en/rates-and-indicators/exchange-rates',
 'https://backfund.net/profile/financial-sector-conduct-authority-fsca',
 'https://www.resbank.co.za/',
 'https://bricscompetition.org/ru/news/south-africas-advertising-regulator-paid-positions-in-rankings-or-search-results-should-be-labelled',
 'https://www.bok.or.kr/eng',
 'https://www.ftc.go.kr/eng/index.do',
 'https://www.fsc.go.kr/eng/index',
 'https://www.nts.go.kr/english/main.do',
 'https://fss.or.kr/eng/main/main.do',
 'https://english.moef.go.kr/',
 'https://www.moj.go.kr/moj_eng/index.do',
 'https://boj.org.jm/',
 'https://www.fsa.go.jp/en/',
 'https://www.boj.or.jp/en/']
